// TODO: DELETE FILE ONCE DATA IS STORED IN DB

import { Position } from '../enums';
import { Player } from '../models';

export const players: Player[] = [
  {
    name: "Ja'Marr Chase",
    draftKingsPlayerId: 1109979,
    position: Position.WR,
    rank: 1,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CIN',
    teamId: 327,
    teamLongName: 'CIN',
  },
  {
    name: 'Saquon Barkley',
    draftKingsPlayerId: 883302,
    position: Position.RB,
    rank: 2,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PHI',
    teamId: 354,
    teamLongName: 'PHI',
  },
  {
    name: 'Bijan Robinson',
    draftKingsPlayerId: 1228244,
    position: Position.RB,
    rank: 3,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'Jahmyr Gibbs',
    draftKingsPlayerId: 1214154,
    position: Position.RB,
    rank: 4,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Justin Jefferson',
    draftKingsPlayerId: 1069535,
    position: Position.WR,
    rank: 5,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIN',
    teamId: 347,
    teamLongName: 'MIN',
  },
  {
    name: 'CeeDee Lamb',
    draftKingsPlayerId: 1062020,
    position: Position.WR,
    rank: 6,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'Puka Nacua',
    draftKingsPlayerId: 1162128,
    position: Position.WR,
    rank: 7,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Amon-Ra St. Brown',
    draftKingsPlayerId: 1127106,
    position: Position.WR,
    rank: 8,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Malik Nabers',
    draftKingsPlayerId: 1286059,
    position: Position.WR,
    rank: 9,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Derrick Henry',
    draftKingsPlayerId: 732145,
    position: Position.RB,
    rank: 10,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Nico Collins',
    draftKingsPlayerId: 1074698,
    position: Position.WR,
    rank: 11,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'Brian Thomas Jr.',
    draftKingsPlayerId: 1286064,
    position: Position.WR,
    rank: 12,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Ashton Jeanty',
    draftKingsPlayerId: 1379646,
    position: Position.RB,
    rank: 13,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: 'Christian McCaffrey',
    draftKingsPlayerId: 830517,
    position: Position.RB,
    rank: 14,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Brock Bowers',
    draftKingsPlayerId: 1285917,
    position: Position.TE,
    rank: 15,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: "De'Von Achane",
    draftKingsPlayerId: 1231820,
    position: Position.RB,
    rank: 16,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Ladd McConkey',
    draftKingsPlayerId: 1218643,
    position: Position.WR,
    rank: 17,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Drake London',
    draftKingsPlayerId: 1178741,
    position: Position.WR,
    rank: 18,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'A.J. Brown',
    draftKingsPlayerId: 944826,
    position: Position.WR,
    rank: 19,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PHI',
    teamId: 354,
    teamLongName: 'PHI',
  },
  {
    name: 'Jonathan Taylor',
    draftKingsPlayerId: 1065406,
    position: Position.RB,
    rank: 20,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Josh Allen',
    draftKingsPlayerId: 868199,
    position: Position.QB,
    rank: 21,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Trey McBride',
    draftKingsPlayerId: 1108161,
    position: Position.TE,
    rank: 22,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ARI',
    teamId: 355,
    teamLongName: 'ARI',
  },
  {
    name: 'Bucky Irving',
    draftKingsPlayerId: 1287923,
    position: Position.RB,
    rank: 23,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'Tee Higgins',
    draftKingsPlayerId: 978579,
    position: Position.WR,
    rank: 24,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CIN',
    teamId: 327,
    teamLongName: 'CIN',
  },
  {
    name: 'Lamar Jackson',
    draftKingsPlayerId: 877745,
    position: Position.QB,
    rank: 25,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Josh Jacobs',
    draftKingsPlayerId: 944416,
    position: Position.RB,
    rank: 26,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Tyreek Hill',
    draftKingsPlayerId: 823156,
    position: Position.WR,
    rank: 27,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Terry McLaurin',
    draftKingsPlayerId: 836116,
    position: Position.WR,
    rank: 28,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Jaxon Smith-Njigba',
    draftKingsPlayerId: 1214087,
    position: Position.WR,
    rank: 29,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Kyren Williams',
    draftKingsPlayerId: 1167361,
    position: Position.RB,
    rank: 30,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Jayden Daniels',
    draftKingsPlayerId: 1161228,
    position: Position.QB,
    rank: 31,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Garrett Wilson',
    draftKingsPlayerId: 1164889,
    position: Position.WR,
    rank: 32,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYJ',
    teamId: 352,
    teamLongName: 'NYJ',
  },
  {
    name: 'Mike Evans',
    draftKingsPlayerId: 593587,
    position: Position.WR,
    rank: 33,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'James Cook',
    draftKingsPlayerId: 1131012,
    position: Position.RB,
    rank: 34,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Marvin Harrison Jr.',
    draftKingsPlayerId: 1287828,
    position: Position.WR,
    rank: 35,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ARI',
    teamId: 355,
    teamLongName: 'ARI',
  },
  {
    name: 'Davante Adams',
    draftKingsPlayerId: 611417,
    position: Position.WR,
    rank: 36,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Breece Hall',
    draftKingsPlayerId: 1162537,
    position: Position.RB,
    rank: 37,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYJ',
    teamId: 352,
    teamLongName: 'NYJ',
  },
  {
    name: 'Chase Brown',
    draftKingsPlayerId: 1123379,
    position: Position.RB,
    rank: 38,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CIN',
    teamId: 327,
    teamLongName: 'CIN',
  },
  {
    name: 'Joe Burrow',
    draftKingsPlayerId: 878785,
    position: Position.QB,
    rank: 39,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CIN',
    teamId: 327,
    teamLongName: 'CIN',
  },
  {
    name: 'Jalen Hurts',
    draftKingsPlayerId: 913271,
    position: Position.QB,
    rank: 40,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PHI',
    teamId: 354,
    teamLongName: 'PHI',
  },
  {
    name: 'DJ Moore',
    draftKingsPlayerId: 877790,
    position: Position.WR,
    rank: 41,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Xavier Worthy',
    draftKingsPlayerId: 1326638,
    position: Position.WR,
    rank: 42,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Joe Mixon',
    draftKingsPlayerId: 820727,
    position: Position.RB,
    rank: 43,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'George Kittle',
    draftKingsPlayerId: 733672,
    position: Position.TE,
    rank: 44,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Sam LaPorta',
    draftKingsPlayerId: 1168926,
    position: Position.TE,
    rank: 45,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Alvin Kamara',
    draftKingsPlayerId: 750846,
    position: Position.RB,
    rank: 46,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'DeVonta Smith',
    draftKingsPlayerId: 1060262,
    position: Position.WR,
    rank: 47,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PHI',
    teamId: 354,
    teamLongName: 'PHI',
  },
  {
    name: 'Patrick Mahomes',
    draftKingsPlayerId: 839031,
    position: Position.QB,
    rank: 48,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Omarion Hampton',
    draftKingsPlayerId: 1398572,
    position: Position.RB,
    rank: 49,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Baker Mayfield',
    draftKingsPlayerId: 748070,
    position: Position.QB,
    rank: 50,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'Jameson Williams',
    draftKingsPlayerId: 1175184,
    position: Position.WR,
    rank: 51,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Chuba Hubbard',
    draftKingsPlayerId: 1062047,
    position: Position.RB,
    rank: 52,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Travis Kelce',
    draftKingsPlayerId: 448240,
    position: Position.TE,
    rank: 53,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'T.J. Hockenson',
    draftKingsPlayerId: 923915,
    position: Position.TE,
    rank: 54,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIN',
    teamId: 347,
    teamLongName: 'MIN',
  },
  {
    name: 'Rashee Rice',
    draftKingsPlayerId: 1173538,
    position: Position.WR,
    rank: 55,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Zay Flowers',
    draftKingsPlayerId: 1177053,
    position: Position.WR,
    rank: 56,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Jonnu Smith',
    draftKingsPlayerId: 743749,
    position: Position.TE,
    rank: 57,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Jared Goff',
    draftKingsPlayerId: 727837,
    position: Position.QB,
    rank: 58,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Chris Godwin',
    draftKingsPlayerId: 835127,
    position: Position.WR,
    rank: 59,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'Kenneth Walker III',
    draftKingsPlayerId: 1164402,
    position: Position.RB,
    rank: 60,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'David Montgomery',
    draftKingsPlayerId: 946739,
    position: Position.RB,
    rank: 61,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Bo Nix',
    draftKingsPlayerId: 1161899,
    position: Position.QB,
    rank: 62,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Mark Andrews',
    draftKingsPlayerId: 820699,
    position: Position.TE,
    rank: 63,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Courtland Sutton',
    draftKingsPlayerId: 838878,
    position: Position.WR,
    rank: 64,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Najee Harris',
    draftKingsPlayerId: 973964,
    position: Position.RB,
    rank: 65,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Travis Hunter Jr.',
    draftKingsPlayerId: 1399275,
    position: Position.WR,
    rank: 66,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'DK Metcalf',
    draftKingsPlayerId: 945633,
    position: Position.WR,
    rank: 67,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PIT',
    teamId: 356,
    teamLongName: 'PIT',
  },
  {
    name: 'Rome Odunze',
    draftKingsPlayerId: 1213727,
    position: Position.WR,
    rank: 68,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'James Conner',
    draftKingsPlayerId: 742390,
    position: Position.RB,
    rank: 69,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ARI',
    teamId: 355,
    teamLongName: 'ARI',
  },
  {
    name: 'Deebo Samuel Sr.',
    draftKingsPlayerId: 835749,
    position: Position.WR,
    rank: 70,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Tetairoa McMillan',
    draftKingsPlayerId: 1380576,
    position: Position.WR,
    rank: 71,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Chris Olave',
    draftKingsPlayerId: 1122592,
    position: Position.WR,
    rank: 72,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Jordan Addison',
    draftKingsPlayerId: 1214250,
    position: Position.WR,
    rank: 73,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIN',
    teamId: 347,
    teamLongName: 'MIN',
  },
  {
    name: 'TreVeyon Henderson',
    draftKingsPlayerId: 1287837,
    position: Position.RB,
    rank: 74,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Kyler Murray',
    draftKingsPlayerId: 879799,
    position: Position.QB,
    rank: 75,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ARI',
    teamId: 355,
    teamLongName: 'ARI',
  },
  {
    name: 'Jaylen Waddle',
    draftKingsPlayerId: 1125749,
    position: Position.WR,
    rank: 76,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'David Njoku',
    draftKingsPlayerId: 832098,
    position: Position.TE,
    rank: 77,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'Jauan Jennings',
    draftKingsPlayerId: 867009,
    position: Position.WR,
    rank: 78,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Jakobi Meyers',
    draftKingsPlayerId: 880151,
    position: Position.WR,
    rank: 79,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: 'Jerry Jeudy',
    draftKingsPlayerId: 973935,
    position: Position.WR,
    rank: 80,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'Tyler Warren',
    draftKingsPlayerId: 1229083,
    position: Position.TE,
    rank: 81,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Aaron Jones Sr.',
    draftKingsPlayerId: 741314,
    position: Position.RB,
    rank: 82,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIN',
    teamId: 347,
    teamLongName: 'MIN',
  },
  {
    name: 'Cooper Kupp',
    draftKingsPlayerId: 698227,
    position: Position.WR,
    rank: 83,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Quinshon Judkins',
    draftKingsPlayerId: 1383807,
    position: Position.RB,
    rank: 84,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'Khalil Shakir',
    draftKingsPlayerId: 1130603,
    position: Position.WR,
    rank: 85,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Tyrone Tracy Jr.',
    draftKingsPlayerId: 1109708,
    position: Position.RB,
    rank: 86,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Ricky Pearsall',
    draftKingsPlayerId: 1161416,
    position: Position.WR,
    rank: 87,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Calvin Ridley',
    draftKingsPlayerId: 884013,
    position: Position.WR,
    rank: 88,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TEN',
    teamId: 336,
    teamLongName: 'TEN',
  },
  {
    name: 'George Pickens',
    draftKingsPlayerId: 1172053,
    position: Position.WR,
    rank: 89,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PIT',
    teamId: 356,
    teamLongName: 'PIT',
  },
  {
    name: 'Jayden Reed',
    draftKingsPlayerId: 1123398,
    position: Position.WR,
    rank: 90,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Stefon Diggs',
    draftKingsPlayerId: 694041,
    position: Position.WR,
    rank: 91,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Caleb Williams',
    draftKingsPlayerId: 1286445,
    position: Position.QB,
    rank: 92,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Jaylen Warren',
    draftKingsPlayerId: 1176443,
    position: Position.RB,
    rank: 93,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PIT',
    teamId: 356,
    teamLongName: 'PIT',
  },
  {
    name: 'Tony Pollard',
    draftKingsPlayerId: 880398,
    position: Position.RB,
    rank: 94,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TEN',
    teamId: 336,
    teamLongName: 'TEN',
  },
  {
    name: 'Evan Engram',
    draftKingsPlayerId: 749185,
    position: Position.TE,
    rank: 95,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Brandon Aiyuk',
    draftKingsPlayerId: 1107034,
    position: Position.WR,
    rank: 96,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Brian Robinson Jr.',
    draftKingsPlayerId: 973966,
    position: Position.RB,
    rank: 97,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Colston Loveland',
    draftKingsPlayerId: 1378821,
    position: Position.TE,
    rank: 98,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Emeka Egbuka',
    draftKingsPlayerId: 1287825,
    position: Position.WR,
    rank: 99,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'Justin Fields',
    draftKingsPlayerId: 1110681,
    position: Position.QB,
    rank: 100,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYJ',
    teamId: 352,
    teamLongName: 'NYJ',
  },
  {
    name: 'Kaleb Johnson',
    draftKingsPlayerId: 1381902,
    position: Position.RB,
    rank: 101,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PIT',
    teamId: 356,
    teamLongName: 'PIT',
  },
  {
    name: 'Brock Purdy',
    draftKingsPlayerId: 1121761,
    position: Position.QB,
    rank: 102,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Rhamondre Stevenson',
    draftKingsPlayerId: 1174682,
    position: Position.RB,
    rank: 103,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Matthew Golden',
    draftKingsPlayerId: 1379267,
    position: Position.WR,
    rank: 104,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Justin Herbert',
    draftKingsPlayerId: 910562,
    position: Position.QB,
    rank: 105,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Isiah Pacheco',
    draftKingsPlayerId: 1106832,
    position: Position.RB,
    rank: 106,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Travis Etienne Jr.',
    draftKingsPlayerId: 978577,
    position: Position.RB,
    rank: 107,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Josh Downs',
    draftKingsPlayerId: 1215077,
    position: Position.WR,
    rank: 108,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Zach Charbonnet',
    draftKingsPlayerId: 1164530,
    position: Position.RB,
    rank: 109,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Dak Prescott',
    draftKingsPlayerId: 591816,
    position: Position.QB,
    rank: 110,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'Jordan Love',
    draftKingsPlayerId: 912137,
    position: Position.QB,
    rank: 111,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Tucker Kraft',
    draftKingsPlayerId: 1181874,
    position: Position.TE,
    rank: 112,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Jalen McMillan',
    draftKingsPlayerId: 1213726,
    position: Position.WR,
    rank: 113,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'C.J. Stroud',
    draftKingsPlayerId: 1214084,
    position: Position.QB,
    rank: 114,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'Cam Skattebo',
    draftKingsPlayerId: 1280316,
    position: Position.RB,
    rank: 115,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Luther Burden III',
    draftKingsPlayerId: 1377732,
    position: Position.WR,
    rank: 116,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Christian Kirk',
    draftKingsPlayerId: 865801,
    position: Position.WR,
    rank: 117,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'Michael Pittman Jr.',
    draftKingsPlayerId: 911348,
    position: Position.WR,
    rank: 118,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: "D'Andre Swift",
    draftKingsPlayerId: 1069808,
    position: Position.RB,
    rank: 119,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Isaiah Likely',
    draftKingsPlayerId: 1125111,
    position: Position.TE,
    rank: 120,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Drake Maye',
    draftKingsPlayerId: 1286803,
    position: Position.QB,
    rank: 121,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Darnell Mooney',
    draftKingsPlayerId: 912027,
    position: Position.WR,
    rank: 122,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'Jordan Mason',
    draftKingsPlayerId: 1116001,
    position: Position.RB,
    rank: 123,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIN',
    teamId: 347,
    teamLongName: 'MIN',
  },
  {
    name: 'Dalton Kincaid',
    draftKingsPlayerId: 1135513,
    position: Position.TE,
    rank: 124,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Dallas Goedert',
    draftKingsPlayerId: 791365,
    position: Position.TE,
    rank: 125,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PHI',
    teamId: 354,
    teamLongName: 'PHI',
  },
  {
    name: 'Rashid Shaheed',
    draftKingsPlayerId: 923412,
    position: Position.WR,
    rank: 126,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Dylan Sampson',
    draftKingsPlayerId: 1399910,
    position: Position.RB,
    rank: 127,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'RJ Harvey',
    draftKingsPlayerId: 1172401,
    position: Position.RB,
    rank: 128,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Marvin Mims Jr.',
    draftKingsPlayerId: 1213799,
    position: Position.WR,
    rank: 129,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Rashod Bateman',
    draftKingsPlayerId: 1108208,
    position: Position.WR,
    rank: 130,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Tank Bigsby',
    draftKingsPlayerId: 1215035,
    position: Position.RB,
    rank: 131,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Kyle Pitts',
    draftKingsPlayerId: 1123026,
    position: Position.TE,
    rank: 132,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'Hollywood Brown',
    draftKingsPlayerId: 976220,
    position: Position.WR,
    rank: 133,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'J.J. McCarthy',
    draftKingsPlayerId: 1287599,
    position: Position.QB,
    rank: 134,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIN',
    teamId: 347,
    teamLongName: 'MIN',
  },
  {
    name: 'Tua Tagovailoa',
    draftKingsPlayerId: 973947,
    position: Position.QB,
    rank: 135,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Michael Penix Jr.',
    draftKingsPlayerId: 1107478,
    position: Position.QB,
    rank: 136,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'Zach Ertz',
    draftKingsPlayerId: 503177,
    position: Position.TE,
    rank: 137,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Jack Bech',
    draftKingsPlayerId: 1286046,
    position: Position.WR,
    rank: 138,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: 'Keon Coleman',
    draftKingsPlayerId: 1322431,
    position: Position.WR,
    rank: 139,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Adam Thielen',
    draftKingsPlayerId: 733643,
    position: Position.WR,
    rank: 140,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Trevor Lawrence',
    draftKingsPlayerId: 1110711,
    position: Position.QB,
    rank: 141,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Matthew Stafford',
    draftKingsPlayerId: 323205,
    position: Position.QB,
    rank: 142,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Javonte Williams',
    draftKingsPlayerId: 1107881,
    position: Position.RB,
    rank: 143,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'Quentin Johnston',
    draftKingsPlayerId: 1213865,
    position: Position.WR,
    rank: 144,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Tyjae Spears',
    draftKingsPlayerId: 1169430,
    position: Position.RB,
    rank: 145,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TEN',
    teamId: 336,
    teamLongName: 'TEN',
  },
  {
    name: 'Rachaad White',
    draftKingsPlayerId: 1229343,
    position: Position.RB,
    rank: 146,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'Jake Ferguson',
    draftKingsPlayerId: 1065361,
    position: Position.TE,
    rank: 147,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'Bhayshul Tuten',
    draftKingsPlayerId: 1327169,
    position: Position.RB,
    rank: 148,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Romeo Doubs',
    draftKingsPlayerId: 1122653,
    position: Position.WR,
    rank: 149,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Jerome Ford',
    draftKingsPlayerId: 1125737,
    position: Position.RB,
    rank: 150,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'Keenan Allen',
    draftKingsPlayerId: 557210,
    position: Position.WR,
    rank: 151,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Isaac Guerendo',
    draftKingsPlayerId: 1126338,
    position: Position.RB,
    rank: 152,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Jayden Higgins',
    draftKingsPlayerId: 1274492,
    position: Position.WR,
    rank: 153,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'J.K. Dobbins',
    draftKingsPlayerId: 976513,
    position: Position.RB,
    rank: 154,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Sam Darnold',
    draftKingsPlayerId: 880026,
    position: Position.QB,
    rank: 155,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Xavier Legette',
    draftKingsPlayerId: 1180321,
    position: Position.WR,
    rank: 156,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Bryce Young',
    draftKingsPlayerId: 1213257,
    position: Position.QB,
    rank: 157,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Trey Benson',
    draftKingsPlayerId: 1248031,
    position: Position.RB,
    rank: 158,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ARI',
    teamId: 355,
    teamLongName: 'ARI',
  },
  {
    name: 'Cam Ward',
    draftKingsPlayerId: 1228691,
    position: Position.QB,
    rank: 159,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TEN',
    teamId: 336,
    teamLongName: 'TEN',
  },
  {
    name: 'Rico Dowdle',
    draftKingsPlayerId: 933480,
    position: Position.RB,
    rank: 160,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Geno Smith',
    draftKingsPlayerId: 513856,
    position: Position.QB,
    rank: 161,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: 'Cade Otton',
    draftKingsPlayerId: 1049263,
    position: Position.TE,
    rank: 162,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'Tre Harris',
    draftKingsPlayerId: 1214633,
    position: Position.WR,
    rank: 163,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Ray Davis',
    draftKingsPlayerId: 1165229,
    position: Position.RB,
    rank: 164,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Anthony Richardson',
    draftKingsPlayerId: 1215022,
    position: Position.QB,
    rank: 165,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Mike Gesicki',
    draftKingsPlayerId: 836152,
    position: Position.TE,
    rank: 166,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CIN',
    teamId: 327,
    teamLongName: 'CIN',
  },
  {
    name: 'Alec Pierce',
    draftKingsPlayerId: 1107027,
    position: Position.WR,
    rank: 167,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Mason Taylor',
    draftKingsPlayerId: 1381263,
    position: Position.TE,
    rank: 168,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYJ',
    teamId: 352,
    teamLongName: 'NYJ',
  },
  {
    name: 'Jaylen Wright',
    draftKingsPlayerId: 1286513,
    position: Position.RB,
    rank: 169,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Pat Freiermuth',
    draftKingsPlayerId: 1116662,
    position: Position.TE,
    rank: 170,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PIT',
    teamId: 356,
    teamLongName: 'PIT',
  },
  {
    name: 'Devin Neal',
    draftKingsPlayerId: 1293066,
    position: Position.RB,
    rank: 171,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Cole Kmet',
    draftKingsPlayerId: 1066765,
    position: Position.TE,
    rank: 172,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Brenton Strange',
    draftKingsPlayerId: 1164940,
    position: Position.TE,
    rank: 173,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Jalen Coker',
    draftKingsPlayerId: 1218753,
    position: Position.WR,
    rank: 174,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Austin Ekeler',
    draftKingsPlayerId: 790004,
    position: Position.RB,
    rank: 175,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Tyler Allgeier',
    draftKingsPlayerId: 1131198,
    position: Position.RB,
    rank: 176,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'Cedric Tillman',
    draftKingsPlayerId: 1124664,
    position: Position.WR,
    rank: 177,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: "Wan'Dale Robinson",
    draftKingsPlayerId: 1164875,
    position: Position.WR,
    rank: 178,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Hunter Henry',
    draftKingsPlayerId: 744425,
    position: Position.TE,
    rank: 179,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Blake Corum',
    draftKingsPlayerId: 1229540,
    position: Position.RB,
    rank: 180,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Dontayvion Wicks',
    draftKingsPlayerId: 1172428,
    position: Position.WR,
    rank: 181,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'DJ Giddens',
    draftKingsPlayerId: 1303569,
    position: Position.RB,
    rank: 182,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Terrance Ferguson',
    draftKingsPlayerId: 1286179,
    position: Position.TE,
    rank: 183,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'DeAndre Hopkins',
    draftKingsPlayerId: 560241,
    position: Position.WR,
    rank: 184,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Kareem Hunt',
    draftKingsPlayerId: 746613,
    position: Position.RB,
    rank: 185,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Braelon Allen',
    draftKingsPlayerId: 1325231,
    position: Position.RB,
    rank: 186,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYJ',
    teamId: 352,
    teamLongName: 'NYJ',
  },
  {
    name: 'Tyler Higbee',
    draftKingsPlayerId: 604176,
    position: Position.TE,
    rank: 187,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'DeMario Douglas',
    draftKingsPlayerId: 1175693,
    position: Position.WR,
    rank: 188,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Jalen Tolbert',
    draftKingsPlayerId: 1066424,
    position: Position.WR,
    rank: 189,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'Nick Chubb',
    draftKingsPlayerId: 822857,
    position: Position.RB,
    rank: 190,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Dalton Schultz',
    draftKingsPlayerId: 830523,
    position: Position.TE,
    rank: 191,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'Amari Cooper',
    draftKingsPlayerId: 650914,
    position: Position.WR,
    rank: 192,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Justice Hill',
    draftKingsPlayerId: 923109,
    position: Position.RB,
    rank: 193,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Joshua Palmer',
    draftKingsPlayerId: 1059612,
    position: Position.WR,
    rank: 194,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Jaylin Noel',
    draftKingsPlayerId: 1286370,
    position: Position.WR,
    rank: 195,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'Ollie Gordon II',
    draftKingsPlayerId: 1377766,
    position: Position.RB,
    rank: 196,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Juwan Johnson',
    draftKingsPlayerId: 884609,
    position: Position.TE,
    rank: 197,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Dyami Brown',
    draftKingsPlayerId: 1107878,
    position: Position.WR,
    rank: 198,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Elic Ayomanor',
    draftKingsPlayerId: 1395319,
    position: Position.WR,
    rank: 199,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TEN',
    teamId: 336,
    teamLongName: 'TEN',
  },
  {
    name: 'Damien Martinez',
    draftKingsPlayerId: 1377751,
    position: Position.RB,
    rank: 200,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Andrei Iosivas',
    draftKingsPlayerId: 1124851,
    position: Position.WR,
    rank: 201,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CIN',
    teamId: 327,
    teamLongName: 'CIN',
  },
  {
    name: 'Isaiah Bond',
    draftKingsPlayerId: 1398503,
    position: Position.WR,
    rank: 202,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Chig Okonkwo',
    draftKingsPlayerId: 1106374,
    position: Position.TE,
    rank: 203,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TEN',
    teamId: 336,
    teamLongName: 'TEN',
  },
  {
    name: 'Harold Fannin Jr.',
    draftKingsPlayerId: 1394752,
    position: Position.TE,
    rank: 204,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'Aaron Rodgers',
    draftKingsPlayerId: 213957,
    position: Position.QB,
    rank: 205,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Derek Carr',
    draftKingsPlayerId: 496083,
    position: Position.QB,
    rank: 206,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Russell Wilson',
    draftKingsPlayerId: 401534,
    position: Position.QB,
    rank: 207,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: "Ja'Tavion Sanders",
    draftKingsPlayerId: 1326628,
    position: Position.TE,
    rank: 208,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Tyler Shough',
    draftKingsPlayerId: 1110306,
    position: Position.QB,
    rank: 209,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Taysom Hill',
    draftKingsPlayerId: 503184,
    position: Position.TE,
    rank: 210,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Raheem Mostert',
    draftKingsPlayerId: 606501,
    position: Position.RB,
    rank: 211,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: 'Elijah Mitchell',
    draftKingsPlayerId: 1050833,
    position: Position.RB,
    rank: 212,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Christian Watson',
    draftKingsPlayerId: 1067918,
    position: Position.WR,
    rank: 213,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Mike Williams',
    draftKingsPlayerId: 733754,
    position: Position.WR,
    rank: 214,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Darius Slayton',
    draftKingsPlayerId: 880557,
    position: Position.WR,
    rank: 215,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Tank Dell',
    draftKingsPlayerId: 1128222,
    position: Position.WR,
    rank: 216,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'Nick Westbrook-Ikhine',
    draftKingsPlayerId: 883259,
    position: Position.WR,
    rank: 217,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Audric Estime',
    draftKingsPlayerId: 1321291,
    position: Position.RB,
    rank: 218,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Jaxson Dart',
    draftKingsPlayerId: 1286260,
    position: Position.QB,
    rank: 219,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Adonai Mitchell',
    draftKingsPlayerId: 1285908,
    position: Position.WR,
    rank: 220,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Xavier Restrepo',
    draftKingsPlayerId: 1214183,
    position: Position.WR,
    rank: 221,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Noah Gray',
    draftKingsPlayerId: 1056981,
    position: Position.TE,
    rank: 222,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Jalen Royals',
    draftKingsPlayerId: 1403491,
    position: Position.WR,
    rank: 223,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Brashard Smith',
    draftKingsPlayerId: 1313668,
    position: Position.RB,
    rank: 224,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Brandin Cooks',
    draftKingsPlayerId: 607864,
    position: Position.WR,
    rank: 225,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Will Shipley',
    draftKingsPlayerId: 1287636,
    position: Position.RB,
    rank: 226,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PHI',
    teamId: 354,
    teamLongName: 'PHI',
  },
  {
    name: 'Daniel Jones',
    draftKingsPlayerId: 879981,
    position: Position.QB,
    rank: 227,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'IND',
    teamId: 338,
    teamLongName: 'IND',
  },
  {
    name: 'Marquez Valdes-Scantling',
    draftKingsPlayerId: 742382,
    position: Position.WR,
    rank: 228,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'MarShawn Lloyd',
    draftKingsPlayerId: 1213414,
    position: Position.RB,
    rank: 229,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Jaleel McLaughlin',
    draftKingsPlayerId: 1271738,
    position: Position.RB,
    rank: 230,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Michael Wilson',
    draftKingsPlayerId: 1123529,
    position: Position.WR,
    rank: 231,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ARI',
    teamId: 355,
    teamLongName: 'ARI',
  },
  {
    name: 'Theo Johnson',
    draftKingsPlayerId: 1214414,
    position: Position.TE,
    rank: 232,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Tyler Conklin',
    draftKingsPlayerId: 861278,
    position: Position.TE,
    rank: 233,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Tutu Atwell',
    draftKingsPlayerId: 1106760,
    position: Position.WR,
    rank: 234,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Kyle Williams',
    draftKingsPlayerId: 1227157,
    position: Position.WR,
    rank: 235,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Kirk Cousins',
    draftKingsPlayerId: 403308,
    position: Position.QB,
    rank: 236,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'Jameis Winston',
    draftKingsPlayerId: 691536,
    position: Position.QB,
    rank: 237,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Troy Franklin',
    draftKingsPlayerId: 1286176,
    position: Position.WR,
    rank: 238,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Tre Tucker',
    draftKingsPlayerId: 1164979,
    position: Position.WR,
    rank: 239,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: 'Jordan Whittington',
    draftKingsPlayerId: 1163273,
    position: Position.WR,
    rank: 240,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Olamide Zaccheaus',
    draftKingsPlayerId: 883976,
    position: Position.WR,
    rank: 241,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Devaughn Vele',
    draftKingsPlayerId: 1164788,
    position: Position.WR,
    rank: 242,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DEN',
    teamId: 332,
    teamLongName: 'DEN',
  },
  {
    name: 'Kendre Miller',
    draftKingsPlayerId: 1213867,
    position: Position.RB,
    rank: 243,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NO',
    teamId: 350,
    teamLongName: 'NO',
  },
  {
    name: 'Kenneth Gainwell',
    draftKingsPlayerId: 1130705,
    position: Position.RB,
    rank: 244,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PIT',
    teamId: 356,
    teamLongName: 'PIT',
  },
  {
    name: 'Jonathon Brooks',
    draftKingsPlayerId: 1326601,
    position: Position.RB,
    rank: 245,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Miles Sanders',
    draftKingsPlayerId: 924261,
    position: Position.RB,
    rank: 246,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'JuJu Smith-Schuster',
    draftKingsPlayerId: 835909,
    position: Position.WR,
    rank: 247,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'KC',
    teamId: 339,
    teamLongName: 'KC',
  },
  {
    name: 'Noah Fant',
    draftKingsPlayerId: 923911,
    position: Position.TE,
    rank: 248,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Tyler Lockett',
    draftKingsPlayerId: 605242,
    position: Position.WR,
    rank: 249,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TEN',
    teamId: 336,
    teamLongName: 'TEN',
  },
  {
    name: 'Kayshon Boutte',
    draftKingsPlayerId: 1213362,
    position: Position.WR,
    rank: 250,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Sean Tucker',
    draftKingsPlayerId: 1228633,
    position: Position.RB,
    rank: 251,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'TB',
    teamId: 362,
    teamLongName: 'TB',
  },
  {
    name: 'Ray-Ray McCloud III',
    draftKingsPlayerId: 867759,
    position: Position.WR,
    rank: 252,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'ATL',
    teamId: 323,
    teamLongName: 'ATL',
  },
  {
    name: 'Gabe Davis',
    draftKingsPlayerId: 976761,
    position: Position.WR,
    rank: 253,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Kalif Raymond',
    draftKingsPlayerId: 692660,
    position: Position.WR,
    rank: 254,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Luke McCaffrey',
    draftKingsPlayerId: 1164846,
    position: Position.WR,
    rank: 255,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Elijah Arroyo',
    draftKingsPlayerId: 1286840,
    position: Position.TE,
    rank: 256,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'KaVontae Turpin',
    draftKingsPlayerId: 865958,
    position: Position.WR,
    rank: 257,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'Jalen Nailor',
    draftKingsPlayerId: 1126817,
    position: Position.WR,
    rank: 258,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIN',
    teamId: 347,
    teamLongName: 'MIN',
  },
  {
    name: 'Dawson Knox',
    draftKingsPlayerId: 884083,
    position: Position.TE,
    rank: 259,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Trevor Etienne',
    draftKingsPlayerId: 1394803,
    position: Position.RB,
    rank: 260,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CAR',
    teamId: 364,
    teamLongName: 'CAR',
  },
  {
    name: 'Jalen Milroe',
    draftKingsPlayerId: 1290102,
    position: Position.QB,
    rank: 261,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Jaydon Blue',
    draftKingsPlayerId: 1378898,
    position: Position.RB,
    rank: 262,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DAL',
    teamId: 331,
    teamLongName: 'DAL',
  },
  {
    name: 'Allen Lazard',
    draftKingsPlayerId: 837958,
    position: Position.WR,
    rank: 263,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYJ',
    teamId: 352,
    teamLongName: 'NYJ',
  },
  {
    name: 'Devin Singletary',
    draftKingsPlayerId: 916466,
    position: Position.RB,
    rank: 264,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NYG',
    teamId: 351,
    teamLongName: 'NYG',
  },
  {
    name: 'Will Dissly',
    draftKingsPlayerId: 837806,
    position: Position.TE,
    rank: 265,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAC',
    teamId: 357,
    teamLongName: 'LAC',
  },
  {
    name: 'Roschon Johnson',
    draftKingsPlayerId: 1163265,
    position: Position.RB,
    rank: 266,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CHI',
    teamId: 326,
    teamLongName: 'CHI',
  },
  {
    name: 'Jordan James',
    draftKingsPlayerId: 1400657,
    position: Position.RB,
    rank: 267,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Curtis Samuel',
    draftKingsPlayerId: 821389,
    position: Position.WR,
    rank: 268,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Mack Hollins',
    draftKingsPlayerId: 702808,
    position: Position.WR,
    rank: 269,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Ty Johnson',
    draftKingsPlayerId: 877784,
    position: Position.RB,
    rank: 270,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BUF',
    teamId: 324,
    teamLongName: 'BUF',
  },
  {
    name: 'Shedeur Sanders',
    draftKingsPlayerId: 1272321,
    position: Position.QB,
    rank: 271,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'Zack Moss',
    draftKingsPlayerId: 913170,
    position: Position.RB,
    rank: 272,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CIN',
    teamId: 327,
    teamLongName: 'CIN',
  },
  {
    name: 'AJ Dillon',
    draftKingsPlayerId: 1060545,
    position: Position.RB,
    rank: 273,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PHI',
    teamId: 354,
    teamLongName: 'PHI',
  },
  {
    name: 'Demarcus Robinson',
    draftKingsPlayerId: 727279,
    position: Position.WR,
    rank: 274,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SF',
    teamId: 359,
    teamLongName: 'SF',
  },
  {
    name: 'Joe Flacco',
    draftKingsPlayerId: 216342,
    position: Position.QB,
    rank: 275,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'CLE',
    teamId: 329,
    teamLongName: 'CLE',
  },
  {
    name: 'John Metchie III',
    draftKingsPlayerId: 1160348,
    position: Position.WR,
    rank: 276,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'HOU',
    teamId: 325,
    teamLongName: 'HOU',
  },
  {
    name: 'Parker Washington',
    draftKingsPlayerId: 1229074,
    position: Position.WR,
    rank: 277,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'JAX',
    teamId: 365,
    teamLongName: 'JAX',
  },
  {
    name: 'Noah Brown',
    draftKingsPlayerId: 836103,
    position: Position.WR,
    rank: 278,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'WAS',
    teamId: 363,
    teamLongName: 'WAS',
  },
  {
    name: 'Savion Williams',
    draftKingsPlayerId: 1213872,
    position: Position.WR,
    rank: 279,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'GB',
    teamId: 335,
    teamLongName: 'GB',
  },
  {
    name: 'Ameer Abdullah',
    draftKingsPlayerId: 590796,
    position: Position.RB,
    rank: 280,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'FA',
    teamId: 252714,
    teamLongName: 'FA',
  },
  {
    name: 'Antonio Gibson',
    draftKingsPlayerId: 1107826,
    position: Position.RB,
    rank: 281,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
  {
    name: 'Tim Patrick',
    draftKingsPlayerId: 838179,
    position: Position.WR,
    rank: 282,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'DET',
    teamId: 334,
    teamLongName: 'DET',
  },
  {
    name: 'Malik Washington',
    draftKingsPlayerId: 1173255,
    position: Position.WR,
    rank: 283,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'MIA',
    teamId: 345,
    teamLongName: 'MIA',
  },
  {
    name: 'Jarquez Hunter',
    draftKingsPlayerId: 1319185,
    position: Position.RB,
    rank: 284,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LAR',
    teamId: 343,
    teamLongName: 'LAR',
  },
  {
    name: 'Keaton Mitchell',
    draftKingsPlayerId: 1222789,
    position: Position.RB,
    rank: 285,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'BAL',
    teamId: 366,
    teamLongName: 'BAL',
  },
  {
    name: 'Tory Horton',
    draftKingsPlayerId: 1223393,
    position: Position.WR,
    rank: 286,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'SEA',
    teamId: 361,
    teamLongName: 'SEA',
  },
  {
    name: 'Michael Mayer',
    draftKingsPlayerId: 1232592,
    position: Position.TE,
    rank: 287,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'LV',
    teamId: 341,
    teamLongName: 'LV',
  },
  {
    name: 'Calvin Austin III',
    draftKingsPlayerId: 1062765,
    position: Position.WR,
    rank: 288,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'PIT',
    teamId: 356,
    teamLongName: 'PIT',
  },
  {
    name: "Ja'Lynn Polk",
    draftKingsPlayerId: 1213881,
    position: Position.WR,
    rank: 289,
    reasonsForConcern: '',
    reasonsForOptimism: '',
    teamAbbreviation: 'NE',
    teamId: 348,
    teamLongName: 'NE',
  },
];
