import { SimpleLineup } from '../../models';

export const lineupsForQb1: SimpleLineup[] = [
  {
    lineupId: '40649920-0',
    lineupGrade: 82.444,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650636',
      nameAbbrev: 'H. Henry',
      name: 'Hunter Henry',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650845',
      nameAbbrev: 'Jets',
      name: 'Jets',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-1',
    lineupGrade: 82.111,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650224',
      nameAbbrev: 'J. Smith-Njigba',
      name: 'Jaxon Smith-Njigba',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650654',
      nameAbbrev: 'I. Likely',
      name: 'Isaiah Likely',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-2',
    lineupGrade: 82.111,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650234',
      nameAbbrev: 'N. Collins',
      name: 'Nico Collins',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650654',
      nameAbbrev: 'I. Likely',
      name: 'Isaiah Likely',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-3',
    lineupGrade: 82.556,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650636',
      nameAbbrev: 'H. Henry',
      name: 'Hunter Henry',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-4',
    lineupGrade: 83.556,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-5',
    lineupGrade: 83,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649982',
      nameAbbrev: 'C. McCaffrey',
      name: 'Christian McCaffrey',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650302',
      nameAbbrev: 'D. Douglas',
      name: 'DeMario Douglas',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650646',
      nameAbbrev: 'A. Barner',
      name: 'AJ Barner',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-6',
    lineupGrade: 81.889,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650646',
      nameAbbrev: 'A. Barner',
      name: 'AJ Barner',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650342',
      nameAbbrev: 'J. Coker',
      name: 'Jalen Coker',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650837',
      nameAbbrev: 'Seahawks',
      name: 'Seahawks',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-7',
    lineupGrade: 83.444,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650636',
      nameAbbrev: 'H. Henry',
      name: 'Hunter Henry',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650851',
      nameAbbrev: 'Saints',
      name: 'Saints',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-8',
    lineupGrade: 83.222,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-9',
    lineupGrade: 82.444,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650302',
      nameAbbrev: 'D. Douglas',
      name: 'DeMario Douglas',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650851',
      nameAbbrev: 'Saints',
      name: 'Saints',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-10',
    lineupGrade: 81.333,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649982',
      nameAbbrev: 'C. McCaffrey',
      name: 'Christian McCaffrey',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650302',
      nameAbbrev: 'D. Douglas',
      name: 'DeMario Douglas',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650250',
      nameAbbrev: 'T. McMillan',
      name: 'Tetairoa McMillan',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-11',
    lineupGrade: 81.889,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650274',
      nameAbbrev: 'J. Williams',
      name: 'Jameson Williams',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650264',
      nameAbbrev: 'M. Harrison Jr.',
      name: 'Marvin Harrison Jr.',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650839',
      nameAbbrev: 'Lions',
      name: 'Lions',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-12',
    lineupGrade: 81.222,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650234',
      nameAbbrev: 'N. Collins',
      name: 'Nico Collins',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650642',
      nameAbbrev: 'M. Taylor',
      name: 'Mason Taylor',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650250',
      nameAbbrev: 'T. McMillan',
      name: 'Tetairoa McMillan',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650838',
      nameAbbrev: 'Panthers',
      name: 'Panthers',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-13',
    lineupGrade: 79.667,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650302',
      nameAbbrev: 'D. Douglas',
      name: 'DeMario Douglas',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650234',
      nameAbbrev: 'N. Collins',
      name: 'Nico Collins',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650264',
      nameAbbrev: 'M. Harrison Jr.',
      name: 'Marvin Harrison Jr.',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650838',
      nameAbbrev: 'Panthers',
      name: 'Panthers',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649920-14',
    lineupGrade: 79.222,
    qb: {
      id: '40649920',
      nameAbbrev: 'D. Maye',
      name: 'Drake Maye',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649982',
      nameAbbrev: 'C. McCaffrey',
      name: 'Christian McCaffrey',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650274',
      nameAbbrev: 'J. Williams',
      name: 'Jameson Williams',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650642',
      nameAbbrev: 'M. Taylor',
      name: 'Mason Taylor',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650266',
      nameAbbrev: 'R. Shaheed',
      name: 'Rashid Shaheed',
      onlyUseInLargerFieldContests: true,
    },
    dst: {
      id: '40650837',
      nameAbbrev: 'Seahawks',
      name: 'Seahawks',
      onlyUseInLargerFieldContests: false,
    },
  },
];
export const lineupsForQb2: SimpleLineup[] = [
  {
    lineupId: '40649923-0',
    lineupGrade: 84.333,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650624',
      nameAbbrev: 'C. Loveland',
      name: 'Colston Loveland',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-1',
    lineupGrade: 84.444,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650624',
      nameAbbrev: 'C. Loveland',
      name: 'Colston Loveland',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650845',
      nameAbbrev: 'Jets',
      name: 'Jets',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-2',
    lineupGrade: 81.778,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650630',
      nameAbbrev: 'T. Johnson',
      name: 'Theo Johnson',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650240',
      nameAbbrev: 'C. Olave',
      name: 'Chris Olave',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-3',
    lineupGrade: 84.444,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-4',
    lineupGrade: 83.778,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-5',
    lineupGrade: 83.556,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649982',
      nameAbbrev: 'C. McCaffrey',
      name: 'Christian McCaffrey',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-6',
    lineupGrade: 82.556,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-7',
    lineupGrade: 83.667,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650630',
      nameAbbrev: 'T. Johnson',
      name: 'Theo Johnson',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-8',
    lineupGrade: 83.333,
    qb: {
      id: '40649923',
      nameAbbrev: 'C. Williams',
      name: 'Caleb Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650224',
      nameAbbrev: 'J. Smith-Njigba',
      name: 'Jaxon Smith-Njigba',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650851',
      nameAbbrev: 'Saints',
      name: 'Saints',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649923-9',
    lineupGrade: 65.556,
    qb: null,
    rb1: null,
    rb2: null,
    wr1: null,
    wr2: null,
    wr3: null,
    te: null,
    flex: null,
    dst: null,
  },
];
export const lineupsForQb3: SimpleLineup[] = [
  {
    lineupId: '40649918-0',
    lineupGrade: 81.444,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650226',
      nameAbbrev: 'A. St. Brown',
      name: 'Amon-Ra St. Brown',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650654',
      nameAbbrev: 'I. Likely',
      name: 'Isaiah Likely',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649918-1',
    lineupGrade: 81,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650228',
      nameAbbrev: 'J. Jefferson',
      name: 'Justin Jefferson',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650654',
      nameAbbrev: 'I. Likely',
      name: 'Isaiah Likely',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650240',
      nameAbbrev: 'C. Olave',
      name: 'Chris Olave',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649918-2',
    lineupGrade: 82.111,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650228',
      nameAbbrev: 'J. Jefferson',
      name: 'Justin Jefferson',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650654',
      nameAbbrev: 'I. Likely',
      name: 'Isaiah Likely',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650234',
      nameAbbrev: 'N. Collins',
      name: 'Nico Collins',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650844',
      nameAbbrev: 'Browns',
      name: 'Browns',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649918-3',
    lineupGrade: 82.667,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650278',
      nameAbbrev: 'P. Washington',
      name: 'Parker Washington',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650839',
      nameAbbrev: 'Lions',
      name: 'Lions',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649918-4',
    lineupGrade: 81.889,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649982',
      nameAbbrev: 'C. McCaffrey',
      name: 'Christian McCaffrey',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650278',
      nameAbbrev: 'P. Washington',
      name: 'Parker Washington',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650837',
      nameAbbrev: 'Seahawks',
      name: 'Seahawks',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649918-5',
    lineupGrade: 81.778,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650264',
      nameAbbrev: 'M. Harrison Jr.',
      name: 'Marvin Harrison Jr.',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650851',
      nameAbbrev: 'Saints',
      name: 'Saints',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649918-6',
    lineupGrade: 65.444,
    qb: null,
    rb1: null,
    rb2: null,
    wr1: null,
    wr2: null,
    wr3: null,
    te: null,
    flex: null,
    dst: null,
  },
  {
    lineupId: '40649918-7',
    lineupGrade: 81,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649986',
      nameAbbrev: 'J. Cook III',
      name: 'James Cook III',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650654',
      nameAbbrev: 'I. Likely',
      name: 'Isaiah Likely',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650342',
      nameAbbrev: 'J. Coker',
      name: 'Jalen Coker',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650837',
      nameAbbrev: 'Seahawks',
      name: 'Seahawks',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649918-8',
    lineupGrade: 46.444,
    qb: null,
    rb1: null,
    rb2: null,
    wr1: null,
    wr2: null,
    wr3: null,
    te: null,
    flex: null,
    dst: null,
  },
  {
    lineupId: '40649918-9',
    lineupGrade: 80.333,
    qb: {
      id: '40649918',
      nameAbbrev: 'L. Jackson',
      name: 'Lamar Jackson',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650260',
      nameAbbrev: 'J. Addison',
      name: 'Jordan Addison',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650234',
      nameAbbrev: 'N. Collins',
      name: 'Nico Collins',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650638',
      nameAbbrev: 'M. Andrews',
      name: 'Mark Andrews',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650845',
      nameAbbrev: 'Jets',
      name: 'Jets',
      onlyUseInLargerFieldContests: false,
    },
  },
];
export const lineupsForQb4: SimpleLineup[] = [
  {
    lineupId: '40649917-0',
    lineupGrade: 82.444,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650620',
      nameAbbrev: 'D. Kincaid',
      name: 'Dalton Kincaid',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-1',
    lineupGrade: 81.556,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650274',
      nameAbbrev: 'J. Williams',
      name: 'Jameson Williams',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650240',
      nameAbbrev: 'C. Olave',
      name: 'Chris Olave',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650840',
      nameAbbrev: 'Ravens',
      name: 'Ravens',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-2',
    lineupGrade: 82.889,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650622',
      nameAbbrev: 'H. Fannin Jr.',
      name: 'Harold Fannin Jr.',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650254',
      nameAbbrev: 'D. Moore',
      name: 'DJ Moore',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650848',
      nameAbbrev: 'Jaguars',
      name: 'Jaguars',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-3',
    lineupGrade: 81.333,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650280',
      nameAbbrev: 'J. Jennings',
      name: 'Jauan Jennings',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650620',
      nameAbbrev: 'D. Kincaid',
      name: 'Dalton Kincaid',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650264',
      nameAbbrev: 'M. Harrison Jr.',
      name: 'Marvin Harrison Jr.',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650845',
      nameAbbrev: 'Jets',
      name: 'Jets',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-4',
    lineupGrade: 82.333,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40650000',
      nameAbbrev: 'R. Dowdle',
      name: 'Rico Dowdle',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649982',
      nameAbbrev: 'C. McCaffrey',
      name: 'Christian McCaffrey',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650274',
      nameAbbrev: 'J. Williams',
      name: 'Jameson Williams',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650278',
      nameAbbrev: 'P. Washington',
      name: 'Parker Washington',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650839',
      nameAbbrev: 'Lions',
      name: 'Lions',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-5',
    lineupGrade: 80.778,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650234',
      nameAbbrev: 'N. Collins',
      name: 'Nico Collins',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650620',
      nameAbbrev: 'D. Kincaid',
      name: 'Dalton Kincaid',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650278',
      nameAbbrev: 'P. Washington',
      name: 'Parker Washington',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650851',
      nameAbbrev: 'Saints',
      name: 'Saints',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-6',
    lineupGrade: 82.111,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650268',
      nameAbbrev: 'K. Shakir',
      name: 'Khalil Shakir',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650238',
      nameAbbrev: 'J. Waddle',
      name: 'Jaylen Waddle',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650232',
      nameAbbrev: 'E. Egbuka',
      name: 'Emeka Egbuka',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650342',
      nameAbbrev: 'J. Coker',
      name: 'Jalen Coker',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650837',
      nameAbbrev: 'Seahawks',
      name: 'Seahawks',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-7',
    lineupGrade: 83.667,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649988',
      nameAbbrev: 'D. Achane',
      name: "De'Von Achane",
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649984',
      nameAbbrev: 'J. Gibbs',
      name: 'Jahmyr Gibbs',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650246',
      nameAbbrev: 'Z. Flowers',
      name: 'Zay Flowers',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650262',
      nameAbbrev: 'W. Robinson',
      name: "Wan'Dale Robinson",
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650284',
      nameAbbrev: 'T. Johnson',
      name: 'Tez Johnson',
      onlyUseInLargerFieldContests: false,
    },
    te: {
      id: '40650646',
      nameAbbrev: 'A. Barner',
      name: 'AJ Barner',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650845',
      nameAbbrev: 'Jets',
      name: 'Jets',
      onlyUseInLargerFieldContests: false,
    },
  },
  {
    lineupId: '40649917-8',
    lineupGrade: 28.778,
    qb: null,
    rb1: null,
    rb2: null,
    wr1: null,
    wr2: null,
    wr3: null,
    te: null,
    flex: null,
    dst: null,
  },
  {
    lineupId: '40649917-9',
    lineupGrade: 81.111,
    qb: {
      id: '40649917',
      nameAbbrev: 'J. Allen',
      name: 'Josh Allen',
      onlyUseInLargerFieldContests: false,
    },
    rb1: {
      id: '40649994',
      nameAbbrev: 'K. Williams',
      name: 'Kyren Williams',
      onlyUseInLargerFieldContests: false,
    },
    rb2: {
      id: '40649992',
      nameAbbrev: 'D. Henry',
      name: 'Derrick Henry',
      onlyUseInLargerFieldContests: false,
    },
    wr1: {
      id: '40650248',
      nameAbbrev: 'S. Diggs',
      name: 'Stefon Diggs',
      onlyUseInLargerFieldContests: false,
    },
    wr2: {
      id: '40650242',
      nameAbbrev: 'G. Wilson',
      name: 'Garrett Wilson',
      onlyUseInLargerFieldContests: false,
    },
    wr3: {
      id: '40650266',
      nameAbbrev: 'R. Shaheed',
      name: 'Rashid Shaheed',
      onlyUseInLargerFieldContests: true,
    },
    te: {
      id: '40650644',
      nameAbbrev: 'D. Njoku',
      name: 'David Njoku',
      onlyUseInLargerFieldContests: false,
    },
    flex: {
      id: '40650244',
      nameAbbrev: 'R. Odunze',
      name: 'Rome Odunze',
      onlyUseInLargerFieldContests: false,
    },
    dst: {
      id: '40650840',
      nameAbbrev: 'Ravens',
      name: 'Ravens',
      onlyUseInLargerFieldContests: false,
    },
  },
];
