// ****** MAIN SLATE ****** \\

// TODO: Delete this file and fetch from DB once app is connected to Firestore
import { Player, Quarterback, RunningBack, PassCatcher } from '../../models';

export const selectedQuarterbacks: Quarterback[] = [
  {
    gameInfo: 'NE@TB',
    gradeOutOfTen: 9,
    id: '40649920',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Drake Maye',
    nameAbbrev: 'D. Maye',
    opposingTeamAbbrev: 'TB',
    position: 'QB',
    salary: 6400,
    teamAbbrev: 'NE',
    maxNumberOfTeammatePasscatchers: 1,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 15,
    passCatcherStacks: [],
    requirePassCatcherFromOpposingTeam: true,
    sortOrder: 1,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 8.9,
    id: '40649923',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Caleb Williams',
    nameAbbrev: 'C. Williams',
    opposingTeamAbbrev: 'NYG',
    position: 'QB',
    salary: 6000,
    teamAbbrev: 'CHI',
    maxNumberOfTeammatePasscatchers: 2,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 10,
    passCatcherStacks: [],
    requirePassCatcherFromOpposingTeam: true,
    sortOrder: 2,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 8.8,
    id: '40649918',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Lamar Jackson',
    nameAbbrev: 'L. Jackson',
    opposingTeamAbbrev: 'MIN',
    position: 'QB',
    salary: 6800,
    teamAbbrev: 'BAL',
    maxNumberOfTeammatePasscatchers: 1,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 10,
    passCatcherStacks: [],
    requirePassCatcherFromOpposingTeam: true,
    sortOrder: 3,
  },
  {
    gameInfo: 'BUF@MIA',
    gradeOutOfTen: 8.7,
    id: '40649917',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Josh Allen',
    nameAbbrev: 'J. Allen',
    opposingTeamAbbrev: 'MIA',
    position: 'QB',
    salary: 7000,
    teamAbbrev: 'BUF',
    maxNumberOfTeammatePasscatchers: 1,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 10,
    passCatcherStacks: [],
    requirePassCatcherFromOpposingTeam: true,
    sortOrder: 4,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 8.6,
    id: '40649926',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Jaxson Dart',
    nameAbbrev: 'J. Dart',
    opposingTeamAbbrev: 'CHI',
    position: 'QB',
    salary: 5700,
    teamAbbrev: 'NYG',
    maxNumberOfTeammatePasscatchers: 1,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 10,
    passCatcherStacks: [],
    requirePassCatcherFromOpposingTeam: true,
    sortOrder: 5,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 8.5,
    id: '40649935',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'J.J. McCarthy',
    nameAbbrev: 'J. McCarthy',
    opposingTeamAbbrev: 'BAL',
    position: 'QB',
    salary: 4900,
    teamAbbrev: 'MIN',
    maxNumberOfTeammatePasscatchers: 2,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 10,
    passCatcherStacks: [],
    requirePassCatcherFromOpposingTeam: false,
    sortOrder: 6,
  },
];

export const selectedRunningBacks: RunningBack[] = [
  {
    gameInfo: 'NO@CAR',
    gradeOutOfTen: 9,
    id: '40650000',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 25,
    name: 'Rico Dowdle',
    nameAbbrev: 'R. Dowdle',
    opposingTeamAbbrev: 'NO',
    position: 'RB',
    salary: 6300,
    teamAbbrev: 'CAR',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'BUF@MIA',
    gradeOutOfTen: 8.9,
    id: '40649986',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 32,
    minOwnershipPercentage: 22,
    name: 'James Cook III',
    nameAbbrev: 'J. Cook III',
    opposingTeamAbbrev: 'MIA',
    position: 'RB',
    salary: 7500,
    teamAbbrev: 'BUF',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'BUF@MIA',
    gradeOutOfTen: 8.8,
    id: '40649988',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 30,
    minOwnershipPercentage: 20,
    name: "De'Von Achane",
    nameAbbrev: 'D. Achane',
    opposingTeamAbbrev: 'BUF',
    position: 'RB',
    salary: 7400,
    teamAbbrev: 'MIA',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'LAR@SF',
    gradeOutOfTen: 8.7,
    id: '40649994',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 27,
    minOwnershipPercentage: 17,
    name: 'Kyren Williams',
    nameAbbrev: 'K. Williams',
    opposingTeamAbbrev: 'SF',
    position: 'RB',
    salary: 6600,
    teamAbbrev: 'LAR',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: true,
    useAsAlternate: false,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 8.6,
    id: '40649992',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 15,
    name: 'Derrick Henry',
    nameAbbrev: 'D. Henry',
    opposingTeamAbbrev: 'MIN',
    position: 'RB',
    salary: 6800,
    teamAbbrev: 'BAL',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'DET@WAS',
    gradeOutOfTen: 8.5,
    id: '40649984',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 22,
    minOwnershipPercentage: 12,
    name: 'Jahmyr Gibbs',
    nameAbbrev: 'J. Gibbs',
    opposingTeamAbbrev: 'WAS',
    position: 'RB',
    salary: 8000,
    teamAbbrev: 'DET',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'LAR@SF',
    gradeOutOfTen: 8.4,
    id: '40649982',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 10,
    name: 'Christian McCaffrey',
    nameAbbrev: 'C. McCaffrey',
    opposingTeamAbbrev: 'LAR',
    position: 'RB',
    salary: 9000,
    teamAbbrev: 'SF',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: true,
    useAsAlternate: false,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 8.3,
    id: '40650014',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 17,
    minOwnershipPercentage: 7,
    name: 'Kyle Monangai',
    nameAbbrev: 'K. Monangai',
    opposingTeamAbbrev: 'NYG',
    position: 'RB',
    salary: 5600,
    teamAbbrev: 'CHI',
    allowOnlyAsFlex: false,
    allowRBFromOpposingTeam: false,
    useAsAlternate: true,
  },
];

export const selectedWideReceivers: PassCatcher[] = [
  {
    gameInfo: 'ARI@SEA',
    gradeOutOfTen: 9,
    id: '40650224',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 30,
    minOwnershipPercentage: 22,
    name: 'Jaxon Smith-Njigba',
    nameAbbrev: 'J. Smith-Njigba',
    opposingTeamAbbrev: 'ARI',
    position: 'WR',
    salary: 8600,
    teamAbbrev: 'SEA',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'LAR@SF',
    gradeOutOfTen: 8.9,
    id: '40650222',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 29,
    minOwnershipPercentage: 21,
    name: 'Puka Nacua',
    nameAbbrev: 'P. Nacua',
    opposingTeamAbbrev: 'SF',
    position: 'WR',
    salary: 8700,
    teamAbbrev: 'LAR',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 8.8,
    id: '40650244',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 28,
    minOwnershipPercentage: 20,
    name: 'Rome Odunze',
    nameAbbrev: 'R. Odunze',
    opposingTeamAbbrev: 'NYG',
    position: 'WR',
    salary: 6000,
    teamAbbrev: 'CHI',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 8.7,
    id: '40650246',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 27,
    minOwnershipPercentage: 19,
    name: 'Zay Flowers',
    nameAbbrev: 'Z. Flowers',
    opposingTeamAbbrev: 'MIN',
    position: 'WR',
    salary: 5900,
    teamAbbrev: 'BAL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NE@TB',
    gradeOutOfTen: 8.6,
    id: '40650232',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 26,
    minOwnershipPercentage: 18,
    name: 'Emeka Egbuka',
    nameAbbrev: 'E. Egbuka',
    opposingTeamAbbrev: 'NE',
    position: 'WR',
    salary: 7000,
    teamAbbrev: 'TB',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 55,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'DET@WAS',
    gradeOutOfTen: 8.5,
    id: '40650226',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 17,
    name: 'Amon-Ra St. Brown',
    nameAbbrev: 'A. St. Brown',
    opposingTeamAbbrev: 'WAS',
    position: 'WR',
    salary: 8400,
    teamAbbrev: 'DET',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'LAR@SF',
    gradeOutOfTen: 8.4,
    id: '40650230',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 24,
    minOwnershipPercentage: 16,
    name: 'Davante Adams',
    nameAbbrev: 'D. Adams',
    opposingTeamAbbrev: 'SF',
    position: 'WR',
    salary: 7700,
    teamAbbrev: 'LAR',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'CLE@NYJ',
    gradeOutOfTen: 8.3,
    id: '40650242',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 23,
    minOwnershipPercentage: 15,
    name: 'Garrett Wilson',
    nameAbbrev: 'G. Wilson',
    opposingTeamAbbrev: 'CLE',
    position: 'WR',
    salary: 6100,
    teamAbbrev: 'NYJ',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'BUF@MIA',
    gradeOutOfTen: 8.2,
    id: '40650238',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 22,
    minOwnershipPercentage: 14,
    name: 'Jaylen Waddle',
    nameAbbrev: 'J. Waddle',
    opposingTeamAbbrev: 'BUF',
    position: 'WR',
    salary: 6400,
    teamAbbrev: 'MIA',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 8.1,
    id: '40650262',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 21,
    minOwnershipPercentage: 13,
    name: "Wan'Dale Robinson",
    nameAbbrev: 'W. Robinson',
    opposingTeamAbbrev: 'CHI',
    position: 'WR',
    salary: 5300,
    teamAbbrev: 'NYG',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'BUF@MIA',
    gradeOutOfTen: 8,
    id: '40650268',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 12,
    name: 'Khalil Shakir',
    nameAbbrev: 'K. Shakir',
    opposingTeamAbbrev: 'MIA',
    position: 'WR',
    salary: 5100,
    teamAbbrev: 'BUF',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'JAX@HOU',
    gradeOutOfTen: 7.9,
    id: '40650234',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 19,
    minOwnershipPercentage: 11,
    name: 'Nico Collins',
    nameAbbrev: 'N. Collins',
    opposingTeamAbbrev: 'JAX',
    position: 'WR',
    salary: 6700,
    teamAbbrev: 'HOU',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NO@CAR',
    gradeOutOfTen: 7.8,
    id: '40650250',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 18,
    minOwnershipPercentage: 10,
    name: 'Tetairoa McMillan',
    nameAbbrev: 'T. McMillan',
    opposingTeamAbbrev: 'NO',
    position: 'WR',
    salary: 5700,
    teamAbbrev: 'CAR',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'LAR@SF',
    gradeOutOfTen: 7.7,
    id: '40650280',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 17,
    minOwnershipPercentage: 9,
    name: 'Jauan Jennings',
    nameAbbrev: 'J. Jennings',
    opposingTeamAbbrev: 'LAR',
    position: 'WR',
    salary: 4600,
    teamAbbrev: 'SF',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'DET@WAS',
    gradeOutOfTen: 7.6,
    id: '40650274',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 16,
    minOwnershipPercentage: 8,
    name: 'Jameson Williams',
    nameAbbrev: 'J. Williams',
    opposingTeamAbbrev: 'WAS',
    position: 'WR',
    salary: 4900,
    teamAbbrev: 'DET',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NE@TB',
    gradeOutOfTen: 7.5,
    id: '40650284',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 15,
    minOwnershipPercentage: 7,
    name: 'Tez Johnson',
    nameAbbrev: 'T. Johnson',
    opposingTeamAbbrev: 'NE',
    position: 'WR',
    salary: 4500,
    teamAbbrev: 'TB',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 45,
    minOwnershipWhenPairedWithOpposingQb: 35,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 7.4,
    id: '40650228',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 14,
    minOwnershipPercentage: 6,
    name: 'Justin Jefferson',
    nameAbbrev: 'J. Jefferson',
    opposingTeamAbbrev: 'BAL',
    position: 'WR',
    salary: 7900,
    teamAbbrev: 'MIN',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'JAX@HOU',
    gradeOutOfTen: 7.3,
    id: '40650278',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'Parker Washington',
    nameAbbrev: 'P. Washington',
    opposingTeamAbbrev: 'HOU',
    position: 'WR',
    salary: 4700,
    teamAbbrev: 'JAX',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NE@TB',
    gradeOutOfTen: 7.2,
    id: '40650248',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 12,
    minOwnershipPercentage: 4,
    name: 'Stefon Diggs',
    nameAbbrev: 'S. Diggs',
    opposingTeamAbbrev: 'TB',
    position: 'WR',
    salary: 5800,
    teamAbbrev: 'NE',
    maxOwnershipWhenPairedWithQb: 50,
    minOwnershipWhenPairedWithQb: 40,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 7.1,
    id: '40650254',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 11,
    minOwnershipPercentage: 3,
    name: 'DJ Moore',
    nameAbbrev: 'D. Moore',
    opposingTeamAbbrev: 'NYG',
    position: 'WR',
    salary: 5500,
    teamAbbrev: 'CHI',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 7,
    id: '40650260',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 10,
    minOwnershipPercentage: 2,
    name: 'Jordan Addison',
    nameAbbrev: 'J. Addison',
    opposingTeamAbbrev: 'BAL',
    position: 'WR',
    salary: 5400,
    teamAbbrev: 'MIN',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'ARI@SEA',
    gradeOutOfTen: 6.9,
    id: '40650264',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 9,
    minOwnershipPercentage: 1,
    name: 'Marvin Harrison Jr.',
    nameAbbrev: 'M. Harrison Jr.',
    opposingTeamAbbrev: 'SEA',
    position: 'WR',
    salary: 5300,
    teamAbbrev: 'ARI',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NO@CAR',
    gradeOutOfTen: 6.8,
    id: '40650240',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 8,
    minOwnershipPercentage: 0,
    name: 'Chris Olave',
    nameAbbrev: 'C. Olave',
    opposingTeamAbbrev: 'CAR',
    position: 'WR',
    salary: 6200,
    teamAbbrev: 'NO',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 6.7,
    id: '40650292',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'Darius Slayton',
    nameAbbrev: 'D. Slayton',
    opposingTeamAbbrev: 'CHI',
    position: 'WR',
    salary: 4300,
    teamAbbrev: 'NYG',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NE@TB',
    gradeOutOfTen: 6.6,
    id: '40650302',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'DeMario Douglas',
    nameAbbrev: 'D. Douglas',
    opposingTeamAbbrev: 'TB',
    position: 'WR',
    salary: 4000,
    teamAbbrev: 'NE',
    maxOwnershipWhenPairedWithQb: 35,
    minOwnershipWhenPairedWithQb: 25,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NO@CAR',
    gradeOutOfTen: 6.5,
    id: '40650342',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 5,
    minOwnershipPercentage: 0,
    name: 'Jalen Coker',
    nameAbbrev: 'J. Coker',
    opposingTeamAbbrev: 'NO',
    position: 'WR',
    salary: 3300,
    teamAbbrev: 'CAR',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'NO@CAR',
    gradeOutOfTen: 6.4,
    id: '40650266',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 4,
    minOwnershipPercentage: 0,
    name: 'Rashid Shaheed',
    nameAbbrev: 'R. Shaheed',
    opposingTeamAbbrev: 'CAR',
    position: 'WR',
    salary: 5200,
    teamAbbrev: 'NO',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    onlyUseInLargerFieldContests: true,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 6.3,
    id: '40650306',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'Rashod Bateman',
    nameAbbrev: 'R. Bateman',
    opposingTeamAbbrev: 'MIN',
    position: 'WR',
    salary: 3900,
    teamAbbrev: 'BAL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 6.2,
    id: '40650338',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'DeAndre Hopkins',
    nameAbbrev: 'D. Hopkins',
    opposingTeamAbbrev: 'MIN',
    position: 'WR',
    salary: 3400,
    teamAbbrev: 'BAL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    onlyUseInLargerFieldContests: false,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 6.1,
    id: '40650374',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'Jalen Nailor',
    nameAbbrev: 'J. Nailor',
    opposingTeamAbbrev: 'BAL',
    position: 'WR',
    salary: 3100,
    teamAbbrev: 'MIN',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    onlyUseInLargerFieldContests: false,
  },
];

export const selectedTightEnds: PassCatcher[] = [
  {
    gameInfo: 'CLE@NYJ',
    gradeOutOfTen: 9,
    id: '40650622',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 17,
    name: 'Harold Fannin Jr.',
    nameAbbrev: 'H. Fannin Jr.',
    opposingTeamAbbrev: 'NYJ',
    position: 'TE',
    salary: 4200,
    teamAbbrev: 'CLE',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'CLE@NYJ',
    gradeOutOfTen: 8.9,
    id: '40650644',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 22,
    minOwnershipPercentage: 14,
    name: 'David Njoku',
    nameAbbrev: 'D. Njoku',
    opposingTeamAbbrev: 'NYJ',
    position: 'TE',
    salary: 3200,
    teamAbbrev: 'CLE',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'CLE@NYJ',
    gradeOutOfTen: 8.8,
    id: '40650642',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 19,
    minOwnershipPercentage: 11,
    name: 'Mason Taylor',
    nameAbbrev: 'M. Taylor',
    opposingTeamAbbrev: 'CLE',
    position: 'TE',
    salary: 3200,
    teamAbbrev: 'NYJ',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'ARI@SEA',
    gradeOutOfTen: 8.7,
    id: '40650614',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 16,
    minOwnershipPercentage: 8,
    name: 'Trey McBride',
    nameAbbrev: 'T. McBride',
    opposingTeamAbbrev: 'SEA',
    position: 'TE',
    salary: 6000,
    teamAbbrev: 'ARI',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 8.6,
    id: '40650654',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'Isaiah Likely',
    nameAbbrev: 'I. Likely',
    opposingTeamAbbrev: 'MIN',
    position: 'TE',
    salary: 2900,
    teamAbbrev: 'BAL',
    maxOwnershipWhenPairedWithQb: 40,
    minOwnershipWhenPairedWithQb: 30,
    maxOwnershipWhenPairedWithOpposingQb: 25,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'LAR@SF',
    gradeOutOfTen: 8.5,
    id: '40650616',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 10,
    minOwnershipPercentage: 2,
    name: 'George Kittle',
    nameAbbrev: 'G. Kittle',
    opposingTeamAbbrev: 'LAR',
    position: 'TE',
    salary: 4500,
    teamAbbrev: 'SF',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'ARI@SEA',
    gradeOutOfTen: 8.4,
    id: '40650646',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 7,
    minOwnershipPercentage: 0,
    name: 'AJ Barner',
    nameAbbrev: 'A. Barner',
    opposingTeamAbbrev: 'ARI',
    position: 'TE',
    salary: 3100,
    teamAbbrev: 'SEA',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'BUF@MIA',
    gradeOutOfTen: 8.3,
    id: '40650620',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'Dalton Kincaid',
    nameAbbrev: 'D. Kincaid',
    opposingTeamAbbrev: 'MIA',
    position: 'TE',
    salary: 4300,
    teamAbbrev: 'BUF',
    maxOwnershipWhenPairedWithQb: 30,
    minOwnershipWhenPairedWithQb: 25,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 8.2,
    id: '40650630',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'Theo Johnson',
    nameAbbrev: 'T. Johnson',
    opposingTeamAbbrev: 'CHI',
    position: 'TE',
    salary: 3800,
    teamAbbrev: 'NYG',
    maxOwnershipWhenPairedWithQb: 30,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 25,
    minOwnershipWhenPairedWithOpposingQb: 1,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 8.1,
    id: '40650638',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'Mark Andrews',
    nameAbbrev: 'M. Andrews',
    opposingTeamAbbrev: 'MIN',
    position: 'TE',
    salary: 3400,
    teamAbbrev: 'BAL',
    maxOwnershipWhenPairedWithQb: 20,
    minOwnershipWhenPairedWithQb: 10,
    maxOwnershipWhenPairedWithOpposingQb: 5,
    minOwnershipWhenPairedWithOpposingQb: 0,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'NYG@CHI',
    gradeOutOfTen: 8,
    id: '40650624',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 3,
    minOwnershipPercentage: 0,
    name: 'Colston Loveland',
    nameAbbrev: 'C. Loveland',
    opposingTeamAbbrev: 'NYG',
    position: 'TE',
    salary: 4100,
    teamAbbrev: 'CHI',
    maxOwnershipWhenPairedWithQb: 20,
    minOwnershipWhenPairedWithQb: 15,
    maxOwnershipWhenPairedWithOpposingQb: 5,
    minOwnershipWhenPairedWithOpposingQb: 0,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'NE@TB',
    gradeOutOfTen: 7.9,
    id: '40650636',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 3,
    minOwnershipPercentage: 0,
    name: 'Hunter Henry',
    nameAbbrev: 'H. Henry',
    opposingTeamAbbrev: 'TB',
    position: 'TE',
    salary: 3500,
    teamAbbrev: 'NE',
    maxOwnershipWhenPairedWithQb: 20,
    minOwnershipWhenPairedWithQb: 17,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
];

export const selectedDSTs: Player[] = [
  {
    gameInfo: 'DET@WAS',
    gradeOutOfTen: 8,
    id: '40650839',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 24,
    minOwnershipPercentage: 16,
    name: 'Lions',
    nameAbbrev: 'Lions',
    opposingTeamAbbrev: 'WAS',
    position: 'DST',
    salary: 3400,
    teamAbbrev: 'DET',
  },
  {
    gameInfo: 'CLE@NYJ',
    gradeOutOfTen: 7.9,
    id: '40650844',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 22,
    minOwnershipPercentage: 14,
    name: 'Browns',
    nameAbbrev: 'Browns',
    opposingTeamAbbrev: 'NYJ',
    position: 'DST',
    salary: 2900,
    teamAbbrev: 'CLE',
  },
  {
    gameInfo: 'CLE@NYJ',
    gradeOutOfTen: 7.8,
    id: '40650845',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 12,
    name: 'Jets',
    nameAbbrev: 'Jets',
    opposingTeamAbbrev: 'CLE',
    position: 'DST',
    salary: 2800,
    teamAbbrev: 'NYJ',
  },
  {
    gameInfo: 'JAX@HOU',
    gradeOutOfTen: 7.7,
    id: '40650848',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 18,
    minOwnershipPercentage: 10,
    name: 'Jaguars',
    nameAbbrev: 'Jaguars',
    opposingTeamAbbrev: 'HOU',
    position: 'DST',
    salary: 2600,
    teamAbbrev: 'JAX',
  },
  {
    gameInfo: 'ARI@SEA',
    gradeOutOfTen: 7.6,
    id: '40650837',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 16,
    minOwnershipPercentage: 8,
    name: 'Seahawks',
    nameAbbrev: 'Seahawks',
    opposingTeamAbbrev: 'ARI',
    position: 'DST',
    salary: 3600,
    teamAbbrev: 'SEA',
  },
  {
    gameInfo: 'NO@CAR',
    gradeOutOfTen: 7.5,
    id: '40650838',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 14,
    minOwnershipPercentage: 6,
    name: 'Panthers',
    nameAbbrev: 'Panthers',
    opposingTeamAbbrev: 'NO',
    position: 'DST',
    salary: 3500,
    teamAbbrev: 'CAR',
  },
  {
    gameInfo: 'BAL@MIN',
    gradeOutOfTen: 7.4,
    id: '40650840',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 12,
    minOwnershipPercentage: 4,
    name: 'Ravens',
    nameAbbrev: 'Ravens',
    opposingTeamAbbrev: 'MIN',
    position: 'DST',
    salary: 3300,
    teamAbbrev: 'BAL',
  },
  {
    gameInfo: 'NO@CAR',
    gradeOutOfTen: 7.3,
    id: '40650851',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 10,
    minOwnershipPercentage: 2,
    name: 'Saints',
    nameAbbrev: 'Saints',
    opposingTeamAbbrev: 'CAR',
    position: 'DST',
    salary: 2400,
    teamAbbrev: 'NO',
  },
];
