import { Lineup } from '../models';

export const lineupsForQb1: Lineup[] = [
  {
    lineupId: '40469967-0',
    lineupGrade: 75.6,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8.6,
      id: '40470032',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Christian McCaffrey',
      nameAbbrev: 'C. McCaffrey',
      opposingTeamAbbrev: 'HOU',
      position: 'RB',
      salary: 9000,
      teamAbbrev: 'SF',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.2,
      id: '40470680',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 10,
      minOwnershipPercentage: 0,
      name: 'Mason Taylor',
      nameAbbrev: 'M. Taylor',
      opposingTeamAbbrev: 'CIN',
      position: 'TE',
      salary: 3500,
      teamAbbrev: 'NYJ',
      maxOwnershipWhenPairedWithQb: 0,
      minOwnershipWhenPairedWithQb: 0,
      maxOwnershipWhenPairedWithOpposingQb: 15,
      minOwnershipWhenPairedWithOpposingQb: 8,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    flex: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8,
      id: '40470380',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 18,
      minOwnershipPercentage: 10,
      name: 'Jaylin Noel',
      nameAbbrev: 'J. Noel',
      opposingTeamAbbrev: 'SF',
      position: 'WR',
      salary: 3500,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 0,
  },
  {
    lineupId: '40469967-1',
    lineupGrade: 61,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 9.2,
      id: '40470034',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 35,
      minOwnershipPercentage: 30,
      name: 'Bijan Robinson',
      nameAbbrev: 'B. Robinson',
      opposingTeamAbbrev: 'MIA',
      position: 'RB',
      salary: 8800,
      teamAbbrev: 'ATL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 9,
      id: '40470686',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 32,
      minOwnershipPercentage: 25,
      name: 'Dalton Schultz',
      nameAbbrev: 'D. Schultz',
      opposingTeamAbbrev: 'SF',
      position: 'TE',
      salary: 3300,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 0,
      minOwnershipWhenPairedWithQb: 0,
      maxOwnershipWhenPairedWithOpposingQb: 0,
      minOwnershipWhenPairedWithOpposingQb: 0,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    flex: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.8,
      id: '40470698',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 18,
      name: 'Colston Loveland',
      nameAbbrev: 'C. Loveland',
      opposingTeamAbbrev: 'BAL',
      position: 'TE',
      salary: 3000,
      teamAbbrev: 'CHI',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 0,
      minOwnershipWhenPairedWithOpposingQb: 0,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.6,
      id: '40470879',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: 'Ravens',
      nameAbbrev: 'Ravens',
      opposingTeamAbbrev: 'CHI',
      position: 'DST',
      salary: 2800,
      teamAbbrev: 'BAL',
    },
    remainingSalary: 200,
  },
  {
    lineupId: '40469967-2',
    lineupGrade: 73.99999999999999,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.7,
      id: '40470056',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Derrick Henry',
      nameAbbrev: 'D. Henry',
      opposingTeamAbbrev: 'CHI',
      position: 'RB',
      salary: 6000,
      teamAbbrev: 'BAL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.2,
      id: '40470680',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 10,
      minOwnershipPercentage: 0,
      name: 'Mason Taylor',
      nameAbbrev: 'M. Taylor',
      opposingTeamAbbrev: 'CIN',
      position: 'TE',
      salary: 3500,
      teamAbbrev: 'NYJ',
      maxOwnershipWhenPairedWithQb: 0,
      minOwnershipWhenPairedWithQb: 0,
      maxOwnershipWhenPairedWithOpposingQb: 15,
      minOwnershipWhenPairedWithOpposingQb: 8,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    flex: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 6.3,
      id: '40470276',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 0,
      minOwnershipPercentage: 0,
      name: 'Drake London',
      nameAbbrev: 'D. London',
      opposingTeamAbbrev: 'MIA',
      position: 'WR',
      salary: 6400,
      teamAbbrev: 'ATL',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 100,
  },
  {
    lineupId: '40469967-3',
    lineupGrade: 75.99999999999999,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.4,
      id: '40470058',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: "D'Andre Swift",
      nameAbbrev: 'D. Swift',
      opposingTeamAbbrev: 'BAL',
      position: 'RB',
      salary: 5900,
      teamAbbrev: 'CHI',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 8.5,
      id: '40470672',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 15,
      minOwnershipPercentage: 7,
      name: 'Kyle Pitts Sr.',
      nameAbbrev: 'K. Pitts Sr.',
      opposingTeamAbbrev: 'MIA',
      position: 'TE',
      salary: 3900,
      teamAbbrev: 'ATL',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    flex: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 8.3,
      id: '40470280',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Courtland Sutton',
      nameAbbrev: 'C. Sutton',
      opposingTeamAbbrev: 'DAL',
      position: 'WR',
      salary: 6200,
      teamAbbrev: 'DEN',
      maxOwnershipWhenPairedWithQb: 70,
      minOwnershipWhenPairedWithQb: 60,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 45,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 0,
  },
  {
    lineupId: '40469967-4',
    lineupGrade: 76.4,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 8.3,
      id: '40470060',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'J.K. Dobbins',
      nameAbbrev: 'J. Dobbins',
      opposingTeamAbbrev: 'DAL',
      position: 'RB',
      salary: 5800,
      teamAbbrev: 'DEN',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.8,
      id: '40470290',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Chris Olave',
      nameAbbrev: 'C. Olave',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 5800,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.5,
      id: '40470278',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: 'Rome Odunze',
      nameAbbrev: 'R. Odunze',
      opposingTeamAbbrev: 'BAL',
      position: 'WR',
      salary: 6300,
      teamAbbrev: 'CHI',
      maxOwnershipWhenPairedWithQb: 85,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 70,
      minOwnershipWhenPairedWithOpposingQb: 45,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8,
      id: '40470380',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 18,
      minOwnershipPercentage: 10,
      name: 'Jaylin Noel',
      nameAbbrev: 'J. Noel',
      opposingTeamAbbrev: 'SF',
      position: 'WR',
      salary: 3500,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 200,
  },
  {
    lineupId: '40469967-5',
    lineupGrade: 76.4,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8.6,
      id: '40470032',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Christian McCaffrey',
      nameAbbrev: 'C. McCaffrey',
      opposingTeamAbbrev: 'HOU',
      position: 'RB',
      salary: 9000,
      teamAbbrev: 'SF',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 9.2,
      id: '40470034',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 35,
      minOwnershipPercentage: 30,
      name: 'Bijan Robinson',
      nameAbbrev: 'B. Robinson',
      opposingTeamAbbrev: 'MIA',
      position: 'RB',
      salary: 8800,
      teamAbbrev: 'ATL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 8.6,
      id: '40470266',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: 'CeeDee Lamb',
      nameAbbrev: 'C. Lamb',
      opposingTeamAbbrev: 'DEN',
      position: 'WR',
      salary: 7800,
      teamAbbrev: 'DAL',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 60,
      minOwnershipWhenPairedWithOpposingQb: 40,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8,
      id: '40470380',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 18,
      minOwnershipPercentage: 10,
      name: 'Jaylin Noel',
      nameAbbrev: 'J. Noel',
      opposingTeamAbbrev: 'SF',
      position: 'WR',
      salary: 3500,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 0,
  },
  {
    lineupId: '40469967-6',
    lineupGrade: 75.69999999999999,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8.6,
      id: '40470032',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Christian McCaffrey',
      nameAbbrev: 'C. McCaffrey',
      opposingTeamAbbrev: 'HOU',
      position: 'RB',
      salary: 9000,
      teamAbbrev: 'SF',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.7,
      id: '40470056',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Derrick Henry',
      nameAbbrev: 'D. Henry',
      opposingTeamAbbrev: 'CHI',
      position: 'RB',
      salary: 6000,
      teamAbbrev: 'BAL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 9,
      id: '40470686',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 32,
      minOwnershipPercentage: 25,
      name: 'Dalton Schultz',
      nameAbbrev: 'D. Schultz',
      opposingTeamAbbrev: 'SF',
      position: 'TE',
      salary: 3300,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 0,
      minOwnershipWhenPairedWithQb: 0,
      maxOwnershipWhenPairedWithOpposingQb: 0,
      minOwnershipWhenPairedWithOpposingQb: 0,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    flex: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 7.3,
      id: '40470270',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 13,
      minOwnershipPercentage: 5,
      name: 'George Pickens',
      nameAbbrev: 'G. Pickens',
      opposingTeamAbbrev: 'DEN',
      position: 'WR',
      salary: 7100,
      teamAbbrev: 'DAL',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 33,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 100,
  },
  {
    lineupId: '40469967-7',
    lineupGrade: 76.89999999999999,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8.6,
      id: '40470032',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Christian McCaffrey',
      nameAbbrev: 'C. McCaffrey',
      opposingTeamAbbrev: 'HOU',
      position: 'RB',
      salary: 9000,
      teamAbbrev: 'SF',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.4,
      id: '40470058',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: "D'Andre Swift",
      nameAbbrev: 'D. Swift',
      opposingTeamAbbrev: 'BAL',
      position: 'RB',
      salary: 5900,
      teamAbbrev: 'CHI',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.8,
      id: '40470290',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Chris Olave',
      nameAbbrev: 'C. Olave',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 5800,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.9,
      id: '40470264',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 27,
      minOwnershipPercentage: 19,
      name: "Ja'Marr Chase",
      nameAbbrev: 'J. Chase',
      opposingTeamAbbrev: 'NYJ',
      position: 'WR',
      salary: 8100,
      teamAbbrev: 'CIN',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 7.9,
      id: '40470332',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 18,
      minOwnershipPercentage: 10,
      name: 'Darnell Mooney',
      nameAbbrev: 'D. Mooney',
      opposingTeamAbbrev: 'MIA',
      position: 'WR',
      salary: 4400,
      teamAbbrev: 'ATL',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.8,
      id: '40470880',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 22,
      name: 'Bengals',
      nameAbbrev: 'Bengals',
      opposingTeamAbbrev: 'NYJ',
      position: 'DST',
      salary: 2700,
      teamAbbrev: 'CIN',
    },
    remainingSalary: 0,
  },
  {
    lineupId: '40469967-8',
    lineupGrade: 68.69999999999999,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8.6,
      id: '40470032',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Christian McCaffrey',
      nameAbbrev: 'C. McCaffrey',
      opposingTeamAbbrev: 'HOU',
      position: 'RB',
      salary: 9000,
      teamAbbrev: 'SF',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 8.3,
      id: '40470060',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'J.K. Dobbins',
      nameAbbrev: 'J. Dobbins',
      opposingTeamAbbrev: 'DAL',
      position: 'RB',
      salary: 5800,
      teamAbbrev: 'DEN',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 8.6,
      id: '40470266',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: 'CeeDee Lamb',
      nameAbbrev: 'C. Lamb',
      opposingTeamAbbrev: 'DEN',
      position: 'WR',
      salary: 7800,
      teamAbbrev: 'DAL',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 60,
      minOwnershipWhenPairedWithOpposingQb: 40,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 9,
      id: '40470286',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 28,
      minOwnershipPercentage: 20,
      name: 'DeVonta Smith',
      nameAbbrev: 'D. Smith',
      opposingTeamAbbrev: 'NYG',
      position: 'WR',
      salary: 5900,
      teamAbbrev: 'PHI',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.8,
      id: '40470880',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 22,
      name: 'Bengals',
      nameAbbrev: 'Bengals',
      opposingTeamAbbrev: 'NYJ',
      position: 'DST',
      salary: 2700,
      teamAbbrev: 'CIN',
    },
    remainingSalary: 0,
  },
  {
    lineupId: '40469967-9',
    lineupGrade: 75,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 9.2,
      id: '40470034',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 35,
      minOwnershipPercentage: 30,
      name: 'Bijan Robinson',
      nameAbbrev: 'B. Robinson',
      opposingTeamAbbrev: 'MIA',
      position: 'RB',
      salary: 8800,
      teamAbbrev: 'ATL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.7,
      id: '40470056',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Derrick Henry',
      nameAbbrev: 'D. Henry',
      opposingTeamAbbrev: 'CHI',
      position: 'RB',
      salary: 6000,
      teamAbbrev: 'BAL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.8,
      id: '40470290',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Chris Olave',
      nameAbbrev: 'C. Olave',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 5800,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 7.3,
      id: '40470270',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 13,
      minOwnershipPercentage: 5,
      name: 'George Pickens',
      nameAbbrev: 'G. Pickens',
      opposingTeamAbbrev: 'DEN',
      position: 'WR',
      salary: 7100,
      teamAbbrev: 'DAL',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 33,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 6.9,
      id: '40470384',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 5,
      name: 'Chimere Dike',
      nameAbbrev: 'C. Dike',
      opposingTeamAbbrev: 'IND',
      position: 'WR',
      salary: 3400,
      teamAbbrev: 'TEN',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 0,
  },
  {
    lineupId: '40469967-10',
    lineupGrade: 76.5,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 9.2,
      id: '40470034',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 35,
      minOwnershipPercentage: 30,
      name: 'Bijan Robinson',
      nameAbbrev: 'B. Robinson',
      opposingTeamAbbrev: 'MIA',
      position: 'RB',
      salary: 8800,
      teamAbbrev: 'ATL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.4,
      id: '40470058',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: "D'Andre Swift",
      nameAbbrev: 'D. Swift',
      opposingTeamAbbrev: 'BAL',
      position: 'RB',
      salary: 5900,
      teamAbbrev: 'CHI',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.8,
      id: '40470290',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Chris Olave',
      nameAbbrev: 'C. Olave',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 5800,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 8.3,
      id: '40470280',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Courtland Sutton',
      nameAbbrev: 'C. Sutton',
      opposingTeamAbbrev: 'DAL',
      position: 'WR',
      salary: 6200,
      teamAbbrev: 'DEN',
      maxOwnershipWhenPairedWithQb: 70,
      minOwnershipWhenPairedWithQb: 60,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 45,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 7,
      id: '40470376',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 5,
      name: 'Jayden Higgins',
      nameAbbrev: 'J. Higgins',
      opposingTeamAbbrev: 'SF',
      position: 'WR',
      salary: 3500,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.8,
      id: '40470880',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 22,
      name: 'Bengals',
      nameAbbrev: 'Bengals',
      opposingTeamAbbrev: 'NYJ',
      position: 'DST',
      salary: 2700,
      teamAbbrev: 'CIN',
    },
    remainingSalary: 300,
  },
  {
    lineupId: '40469967-11',
    lineupGrade: 76.60000000000001,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 9.2,
      id: '40470034',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 35,
      minOwnershipPercentage: 30,
      name: 'Bijan Robinson',
      nameAbbrev: 'B. Robinson',
      opposingTeamAbbrev: 'MIA',
      position: 'RB',
      salary: 8800,
      teamAbbrev: 'ATL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'DAL@DEN',
      gradeOutOfTen: 8.3,
      id: '40470060',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'J.K. Dobbins',
      nameAbbrev: 'J. Dobbins',
      opposingTeamAbbrev: 'DAL',
      position: 'RB',
      salary: 5800,
      teamAbbrev: 'DEN',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.8,
      id: '40470290',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Chris Olave',
      nameAbbrev: 'C. Olave',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 5800,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.5,
      id: '40470278',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 23,
      minOwnershipPercentage: 15,
      name: 'Rome Odunze',
      nameAbbrev: 'R. Odunze',
      opposingTeamAbbrev: 'BAL',
      position: 'WR',
      salary: 6300,
      teamAbbrev: 'CHI',
      maxOwnershipWhenPairedWithQb: 85,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 70,
      minOwnershipWhenPairedWithOpposingQb: 45,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 7,
      id: '40470376',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 5,
      name: 'Jayden Higgins',
      nameAbbrev: 'J. Higgins',
      opposingTeamAbbrev: 'SF',
      position: 'WR',
      salary: 3500,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.8,
      id: '40470880',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 22,
      name: 'Bengals',
      nameAbbrev: 'Bengals',
      opposingTeamAbbrev: 'NYJ',
      position: 'DST',
      salary: 2700,
      teamAbbrev: 'CIN',
    },
    remainingSalary: 300,
  },
  {
    lineupId: '40469967-12',
    lineupGrade: 74.6,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 8.6,
      id: '40470032',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Christian McCaffrey',
      nameAbbrev: 'C. McCaffrey',
      opposingTeamAbbrev: 'HOU',
      position: 'RB',
      salary: 9000,
      teamAbbrev: 'SF',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 7.9,
      id: '40470332',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 18,
      minOwnershipPercentage: 10,
      name: 'Darnell Mooney',
      nameAbbrev: 'D. Mooney',
      opposingTeamAbbrev: 'MIA',
      position: 'WR',
      salary: 4400,
      teamAbbrev: 'ATL',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.6,
      id: '40470684',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 0,
      name: 'Cade Otton',
      nameAbbrev: 'C. Otton',
      opposingTeamAbbrev: 'NO',
      position: 'TE',
      salary: 3400,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 20,
      minOwnershipWhenPairedWithOpposingQb: 10,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    flex: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 6.9,
      id: '40470384',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 5,
      name: 'Chimere Dike',
      nameAbbrev: 'C. Dike',
      opposingTeamAbbrev: 'IND',
      position: 'WR',
      salary: 3400,
      teamAbbrev: 'TEN',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.1,
      id: '40470888',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 12,
      minOwnershipPercentage: 4,
      name: 'Giants',
      nameAbbrev: 'Giants',
      opposingTeamAbbrev: 'PHI',
      position: 'DST',
      salary: 2100,
      teamAbbrev: 'NYG',
    },
    remainingSalary: 100,
  },
  {
    lineupId: '40469967-13',
    lineupGrade: 61,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'MIA@ATL',
      gradeOutOfTen: 9.2,
      id: '40470034',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 35,
      minOwnershipPercentage: 30,
      name: 'Bijan Robinson',
      nameAbbrev: 'B. Robinson',
      opposingTeamAbbrev: 'MIA',
      position: 'RB',
      salary: 8800,
      teamAbbrev: 'ATL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'SF@HOU',
      gradeOutOfTen: 9,
      id: '40470686',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 32,
      minOwnershipPercentage: 25,
      name: 'Dalton Schultz',
      nameAbbrev: 'D. Schultz',
      opposingTeamAbbrev: 'SF',
      position: 'TE',
      salary: 3300,
      teamAbbrev: 'HOU',
      maxOwnershipWhenPairedWithQb: 0,
      minOwnershipWhenPairedWithQb: 0,
      maxOwnershipWhenPairedWithOpposingQb: 0,
      minOwnershipWhenPairedWithOpposingQb: 0,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    flex: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.5,
      id: '40470690',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 15,
      minOwnershipPercentage: 0,
      name: 'Noah Fant',
      nameAbbrev: 'N. Fant',
      opposingTeamAbbrev: 'NYJ',
      position: 'TE',
      salary: 3200,
      teamAbbrev: 'CIN',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 25,
      maxOwnershipWhenPairedWithOpposingQb: 0,
      minOwnershipWhenPairedWithOpposingQb: 0,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
    },
    dst: {
      gameInfo: 'NYJ@CIN',
      gradeOutOfTen: 8.8,
      id: '40470880',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 22,
      name: 'Bengals',
      nameAbbrev: 'Bengals',
      opposingTeamAbbrev: 'NYJ',
      position: 'DST',
      salary: 2700,
      teamAbbrev: 'CIN',
    },
    remainingSalary: 100,
  },
  {
    lineupId: '40469967-14',
    lineupGrade: 69.6,
    qb: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40469967',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 100,
      minOwnershipPercentage: 100,
      name: 'Baker Mayfield',
      nameAbbrev: 'B. Mayfield',
      opposingTeamAbbrev: 'NO',
      position: 'QB',
      salary: 6400,
      teamAbbrev: 'TB',
      maxNumberOfTeammatePasscatchers: 2,
      minNumberOfTeammatePasscatchers: 1,
      numberOfLineupsWithThisPlayer: 15,
      requirePassCatcherFromOpposingTeam: true,
      qbPassCatcherPairings: [],
    },
    rb1: {
      gameInfo: 'TEN@IND',
      gradeOutOfTen: 8.7,
      id: '40470030',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Jonathan Taylor',
      nameAbbrev: 'J. Taylor',
      opposingTeamAbbrev: 'TEN',
      position: 'RB',
      salary: 9500,
      teamAbbrev: 'IND',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    rb2: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.7,
      id: '40470056',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 30,
      minOwnershipPercentage: 25,
      name: 'Derrick Henry',
      nameAbbrev: 'D. Henry',
      opposingTeamAbbrev: 'CHI',
      position: 'RB',
      salary: 6000,
      teamAbbrev: 'BAL',
      allowRBFromOpposingTeam: false,
      useAsAlternate: false,
    },
    wr1: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.7,
      id: '40470272',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 17,
      name: 'Emeka Egbuka',
      nameAbbrev: 'E. Egbuka',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 7000,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 90,
      minOwnershipWhenPairedWithQb: 70,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr2: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.2,
      id: '40470336',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Tez Johnson',
      nameAbbrev: 'T. Johnson',
      opposingTeamAbbrev: 'NO',
      position: 'WR',
      salary: 4300,
      teamAbbrev: 'TB',
      maxOwnershipWhenPairedWithQb: 65,
      minOwnershipWhenPairedWithQb: 50,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    wr3: {
      gameInfo: 'TB@NO',
      gradeOutOfTen: 8.4,
      id: '40470324',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 20,
      minOwnershipPercentage: 12,
      name: 'Rashid Shaheed',
      nameAbbrev: 'R. Shaheed',
      opposingTeamAbbrev: 'TB',
      position: 'WR',
      salary: 4700,
      teamAbbrev: 'NO',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 50,
      minOwnershipWhenPairedWithOpposingQb: 35,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    te: {
      gameInfo: 'CHI@BAL',
      gradeOutOfTen: 8.8,
      id: '40470698',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 25,
      minOwnershipPercentage: 18,
      name: 'Colston Loveland',
      nameAbbrev: 'C. Loveland',
      opposingTeamAbbrev: 'BAL',
      position: 'TE',
      salary: 3000,
      teamAbbrev: 'CHI',
      maxOwnershipWhenPairedWithQb: 50,
      minOwnershipWhenPairedWithQb: 30,
      maxOwnershipWhenPairedWithOpposingQb: 0,
      minOwnershipWhenPairedWithOpposingQb: 0,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    flex: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 9,
      id: '40470286',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 28,
      minOwnershipPercentage: 20,
      name: 'DeVonta Smith',
      nameAbbrev: 'D. Smith',
      opposingTeamAbbrev: 'NYG',
      position: 'WR',
      salary: 5900,
      teamAbbrev: 'PHI',
      maxOwnershipWhenPairedWithQb: 80,
      minOwnershipWhenPairedWithQb: 20,
      maxOwnershipWhenPairedWithOpposingQb: 65,
      minOwnershipWhenPairedWithOpposingQb: 20,
      onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
    },
    dst: {
      gameInfo: 'NYG@PHI',
      gradeOutOfTen: 8.2,
      id: '40470875',
      isSelectedForPlayerPool: false,
      maxOwnershipPercentage: 15,
      minOwnershipPercentage: 7,
      name: 'Eagles',
      nameAbbrev: 'Eagles',
      opposingTeamAbbrev: 'NYG',
      position: 'DST',
      salary: 3200,
      teamAbbrev: 'PHI',
    },
    remainingSalary: 0,
  },
];

export const lineupsForQb2: Lineup[] = [];
export const lineupsForQb3: Lineup[] = [];
export const lineupsForQb4: Lineup[] = [];
