// TODO: Delete this file and fetch from DB once app is connected to Firestore

import { Quarterback, RunningBack } from '../models';

export const selectedQuarterbacks: Quarterback[] = [
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 9,
    id: '40469970',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Bo Nix',
    nameAbbrev: 'B. Nix',
    opposingTeamAbbrev: 'DAL',
    position: 'QB',
    salary: 6000,
    teamAbbrev: 'DEN',
    maxNumberOfTeammatePasscatchers: 2,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 40,
    requirePassCatcherFromOpposingTeam: true,
    qbPassCatcherPairings: [],
  },
  // {
  //   gameInfo: 'BUF@CAR',
  //   gradeOutOfTen: 8.6,
  //   id: '40469983',
  //   isSelectedForPlayerPool: false,
  //   maxOwnershipPercentage: 100,
  //   minOwnershipPercentage: 100,
  //   name: 'Andy Dalton',
  //   nameAbbrev: 'A. Dalton',
  //   opposingTeamAbbrev: 'BUF',
  //   position: 'QB',
  //   salary: 4500,
  //   teamAbbrev: 'CAR',
  //   maxNumberOfTeammatePasscatchers: 2,
  //   minNumberOfTeammatePasscatchers: 1,
  //   numberOfLineupsWithThisPlayer: 18,
  //   requirePassCatcherFromOpposingTeam: false,
  //   qbPassCatcherPairings: [],
  // },
  // {
  //   gameInfo: 'NYJ@CIN',
  //   gradeOutOfTen: 8.5,
  //   id: '40469984',
  //   isSelectedForPlayerPool: false,
  //   maxOwnershipPercentage: 100,
  //   minOwnershipPercentage: 100,
  //   name: 'Tyrod Taylor',
  //   nameAbbrev: 'T. Taylor',
  //   opposingTeamAbbrev: 'CIN',
  //   position: 'QB',
  //   salary: 4500,
  //   teamAbbrev: 'NYJ',
  //   maxNumberOfTeammatePasscatchers: 1,
  //   minNumberOfTeammatePasscatchers: 1,
  //   numberOfLineupsWithThisPlayer: 18,
  //   requirePassCatcherFromOpposingTeam: true,
  //   qbPassCatcherPairings: [],
  // },
  // {
  //   gameInfo: 'TB@NO',
  //   gradeOutOfTen: 8.3,
  //   id: '40469981',
  //   isSelectedForPlayerPool: false,
  //   maxOwnershipPercentage: 100,
  //   minOwnershipPercentage: 100,
  //   name: 'Spencer Rattler',
  //   nameAbbrev: 'S. Rattler',
  //   opposingTeamAbbrev: 'TB',
  //   position: 'QB',
  //   salary: 4700,
  //   teamAbbrev: 'NO',
  //   maxNumberOfTeammatePasscatchers: 1,
  //   minNumberOfTeammatePasscatchers: 1,
  //   numberOfLineupsWithThisPlayer: 18,
  //   requirePassCatcherFromOpposingTeam: true,
  //   qbPassCatcherPairings: [],
  // },
];

export const selectedRunningBacks: RunningBack[] = [
  {
    gameInfo: 'MIA@ATL',
    gradeOutOfTen: 9,
    id: '40470034',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 25,
    name: 'Bijan Robinson',
    nameAbbrev: 'B. Robinson',
    opposingTeamAbbrev: 'MIA',
    position: 'RB',
    salary: 8800,
    teamAbbrev: 'ATL',
    allowRBFromOpposingTeam: false,
  },
  {
    gameInfo: 'TEN@IND',
    gradeOutOfTen: 8.9,
    id: '40470030',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 23,
    name: 'Jonathan Taylor',
    nameAbbrev: 'J. Taylor',
    opposingTeamAbbrev: 'TEN',
    position: 'RB',
    salary: 9500,
    teamAbbrev: 'IND',
    allowRBFromOpposingTeam: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.8,
    id: '40470056',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 20,
    name: 'Derrick Henry',
    nameAbbrev: 'D. Henry',
    opposingTeamAbbrev: 'CHI',
    position: 'RB',
    salary: 6000,
    teamAbbrev: 'BAL',
    allowRBFromOpposingTeam: false,
  },
  {
    gameInfo: 'SF@HOU',
    gradeOutOfTen: 8.7,
    id: '40470032',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 18,
    name: 'Christian McCaffrey',
    nameAbbrev: 'C. McCaffrey',
    opposingTeamAbbrev: 'HOU',
    position: 'RB',
    salary: 9000,
    teamAbbrev: 'SF',
    allowRBFromOpposingTeam: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.6,
    id: '40470058',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 15,
    name: "D'Andre Swift",
    nameAbbrev: 'D. Swift',
    opposingTeamAbbrev: 'BAL',
    position: 'RB',
    salary: 5900,
    teamAbbrev: 'CHI',
    allowRBFromOpposingTeam: false,
  },
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 8.5,
    id: '40470060',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 13,
    name: 'J.K. Dobbins',
    nameAbbrev: 'J. Dobbins',
    opposingTeamAbbrev: 'DAL',
    position: 'RB',
    salary: 5800,
    teamAbbrev: 'DEN',
    allowRBFromOpposingTeam: false,
  },
  {
    gameInfo: 'NYJ@CIN',
    gradeOutOfTen: 8.4,
    id: '40470066',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 10,
    name: 'Chase Brown',
    nameAbbrev: 'C. Brown',
    opposingTeamAbbrev: 'NYJ',
    position: 'RB',
    salary: 5400,
    teamAbbrev: 'CIN',
    allowRBFromOpposingTeam: false,
  },
];
