// TODO: Delete this file and fetch from DB once app is connected to Firestore

import {
  Player,
  Quarterback,
  RunningBack,
  TightEnd,
  WideReceiver,
} from '../models';

export const selectedQuarterbacks: Quarterback[] = [
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 9,
    id: '40469970',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Bo Nix',
    nameAbbrev: 'B. Nix',
    opposingTeamAbbrev: 'DAL',
    position: 'QB',
    salary: 6000,
    teamAbbrev: 'DEN',
    maxNumberOfTeammatePasscatchers: 1,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 39,
    requirePassCatcherFromOpposingTeam: true,
    qbPassCatcherPairings: [],
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.8,
    id: '40469972',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Caleb Williams',
    nameAbbrev: 'C. Williams',
    opposingTeamAbbrev: 'BAL',
    position: 'QB',
    salary: 5600,
    teamAbbrev: 'CHI',
    maxNumberOfTeammatePasscatchers: 2,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 15,
    requirePassCatcherFromOpposingTeam: false,
    qbPassCatcherPairings: [],
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.7,
    id: '40469967',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Baker Mayfield',
    nameAbbrev: 'B. Mayfield',
    opposingTeamAbbrev: 'NO',
    position: 'QB',
    salary: 6400,
    teamAbbrev: 'TB',
    maxNumberOfTeammatePasscatchers: 2,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 15,
    requirePassCatcherFromOpposingTeam: true,
    qbPassCatcherPairings: [],
  },
  {
    gameInfo: 'NYJ@CIN',
    gradeOutOfTen: 8.6,
    id: '40469974',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Joe Flacco',
    nameAbbrev: 'J. Flacco',
    opposingTeamAbbrev: 'NYJ',
    position: 'QB',
    salary: 5400,
    teamAbbrev: 'CIN',
    maxNumberOfTeammatePasscatchers: 2,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 18,
    requirePassCatcherFromOpposingTeam: false,
    qbPassCatcherPairings: [],
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.6,
    id: '40469981',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 100,
    minOwnershipPercentage: 100,
    name: 'Spencer Rattler',
    nameAbbrev: 'S. Rattler',
    opposingTeamAbbrev: 'TB',
    position: 'QB',
    salary: 4700,
    teamAbbrev: 'NO',
    maxNumberOfTeammatePasscatchers: 2,
    minNumberOfTeammatePasscatchers: 1,
    numberOfLineupsWithThisPlayer: 15,
    requirePassCatcherFromOpposingTeam: true,
    qbPassCatcherPairings: [],
  },
];

export const selectedRunningBacks: RunningBack[] = [
  {
    gameInfo: 'MIA@ATL',
    gradeOutOfTen: 9.2,
    id: '40470034',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 35,
    minOwnershipPercentage: 30,
    name: 'Bijan Robinson',
    nameAbbrev: 'B. Robinson',
    opposingTeamAbbrev: 'MIA',
    position: 'RB',
    salary: 8800,
    teamAbbrev: 'ATL',
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.7,
    id: '40470050',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 30,
    minOwnershipPercentage: 25,
    name: 'Rachaad White',
    nameAbbrev: 'R. White',
    opposingTeamAbbrev: 'NO',
    position: 'RB',
    salary: 6400,
    teamAbbrev: 'TB',
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.7,
    id: '40470056',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 30,
    minOwnershipPercentage: 25,
    name: 'Derrick Henry',
    nameAbbrev: 'D. Henry',
    opposingTeamAbbrev: 'CHI',
    position: 'RB',
    salary: 6000,
    teamAbbrev: 'BAL',
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'TEN@IND',
    gradeOutOfTen: 8.7,
    id: '40470030',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 30,
    minOwnershipPercentage: 25,
    name: 'Jonathan Taylor',
    nameAbbrev: 'J. Taylor',
    opposingTeamAbbrev: 'TEN',
    position: 'RB',
    salary: 9500,
    teamAbbrev: 'IND',
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'SF@HOU',
    gradeOutOfTen: 8.6,
    id: '40470032',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 17,
    name: 'Christian McCaffrey',
    nameAbbrev: 'C. McCaffrey',
    opposingTeamAbbrev: 'HOU',
    position: 'RB',
    salary: 9000,
    teamAbbrev: 'SF',
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.4,
    id: '40470058',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 23,
    minOwnershipPercentage: 15,
    name: "D'Andre Swift",
    nameAbbrev: 'D. Swift',
    opposingTeamAbbrev: 'BAL',
    position: 'RB',
    salary: 5900,
    teamAbbrev: 'CHI',
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 8.3,
    id: '40470060',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 12,
    name: 'J.K. Dobbins',
    nameAbbrev: 'J. Dobbins',
    opposingTeamAbbrev: 'DAL',
    position: 'RB',
    salary: 5800,
    teamAbbrev: 'DEN',
    allowRBFromOpposingTeam: false,
    useAsAlternate: false,
  },
];

export const selectedWideReceivers: WideReceiver[] = [
  {
    gameInfo: 'NYG@PHI',
    gradeOutOfTen: 9,
    id: '40470286',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 28,
    minOwnershipPercentage: 20,
    name: 'DeVonta Smith',
    nameAbbrev: 'D. Smith',
    opposingTeamAbbrev: 'NYG',
    position: 'WR',
    salary: 5900,
    teamAbbrev: 'PHI',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'NYJ@CIN',
    gradeOutOfTen: 8.9,
    id: '40470264',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 27,
    minOwnershipPercentage: 19,
    name: "Ja'Marr Chase",
    nameAbbrev: 'J. Chase',
    opposingTeamAbbrev: 'NYJ',
    position: 'WR',
    salary: 8100,
    teamAbbrev: 'CIN',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.8,
    id: '40470290',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 17,
    name: 'Chris Olave',
    nameAbbrev: 'C. Olave',
    opposingTeamAbbrev: 'TB',
    position: 'WR',
    salary: 5800,
    teamAbbrev: 'NO',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.7,
    id: '40470272',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 17,
    name: 'Emeka Egbuka',
    nameAbbrev: 'E. Egbuka',
    opposingTeamAbbrev: 'NO',
    position: 'WR',
    salary: 7000,
    teamAbbrev: 'TB',
    maxOwnershipWhenPairedWithQb: 90,
    minOwnershipWhenPairedWithQb: 70,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 8.6,
    id: '40470266',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 23,
    minOwnershipPercentage: 15,
    name: 'CeeDee Lamb',
    nameAbbrev: 'C. Lamb',
    opposingTeamAbbrev: 'DEN',
    position: 'WR',
    salary: 7800,
    teamAbbrev: 'DAL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 70,
    maxOwnershipWhenPairedWithOpposingQb: 60,
    minOwnershipWhenPairedWithOpposingQb: 40,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.5,
    id: '40470278',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 23,
    minOwnershipPercentage: 15,
    name: 'Rome Odunze',
    nameAbbrev: 'R. Odunze',
    opposingTeamAbbrev: 'BAL',
    position: 'WR',
    salary: 6300,
    teamAbbrev: 'CHI',
    maxOwnershipWhenPairedWithQb: 85,
    minOwnershipWhenPairedWithQb: 70,
    maxOwnershipWhenPairedWithOpposingQb: 70,
    minOwnershipWhenPairedWithOpposingQb: 45,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.4,
    id: '40470324',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 12,
    name: 'Rashid Shaheed',
    nameAbbrev: 'R. Shaheed',
    opposingTeamAbbrev: 'TB',
    position: 'WR',
    salary: 4700,
    teamAbbrev: 'NO',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 50,
    minOwnershipWhenPairedWithOpposingQb: 35,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 8.3,
    id: '40470280',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 12,
    name: 'Courtland Sutton',
    nameAbbrev: 'C. Sutton',
    opposingTeamAbbrev: 'DAL',
    position: 'WR',
    salary: 6200,
    teamAbbrev: 'DEN',
    maxOwnershipWhenPairedWithQb: 70,
    minOwnershipWhenPairedWithQb: 60,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 45,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.2,
    id: '40470336',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 12,
    name: 'Tez Johnson',
    nameAbbrev: 'T. Johnson',
    opposingTeamAbbrev: 'NO',
    position: 'WR',
    salary: 4300,
    teamAbbrev: 'TB',
    maxOwnershipWhenPairedWithQb: 65,
    minOwnershipWhenPairedWithQb: 50,
    maxOwnershipWhenPairedWithOpposingQb: 50,
    minOwnershipWhenPairedWithOpposingQb: 35,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.1,
    id: '40470302',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 18,
    minOwnershipPercentage: 10,
    name: 'Zay Flowers',
    nameAbbrev: 'Z. Flowers',
    opposingTeamAbbrev: 'CHI',
    position: 'WR',
    salary: 5400,
    teamAbbrev: 'BAL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 35,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'SF@HOU',
    gradeOutOfTen: 8,
    id: '40470380',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 18,
    minOwnershipPercentage: 10,
    name: 'Jaylin Noel',
    nameAbbrev: 'J. Noel',
    opposingTeamAbbrev: 'SF',
    position: 'WR',
    salary: 3500,
    teamAbbrev: 'HOU',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'MIA@ATL',
    gradeOutOfTen: 7.9,
    id: '40470332',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 18,
    minOwnershipPercentage: 10,
    name: 'Darnell Mooney',
    nameAbbrev: 'D. Mooney',
    opposingTeamAbbrev: 'MIA',
    position: 'WR',
    salary: 4400,
    teamAbbrev: 'ATL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'BUF@CAR',
    gradeOutOfTen: 7.8,
    id: '40470292',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 18,
    minOwnershipPercentage: 10,
    name: 'Tetairoa McMillan',
    nameAbbrev: 'T. McMillan',
    opposingTeamAbbrev: 'BUF',
    position: 'WR',
    salary: 5700,
    teamAbbrev: 'CAR',
    maxOwnershipWhenPairedWithQb: 85,
    minOwnershipWhenPairedWithQb: 70,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 40,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'CLE@NE',
    gradeOutOfTen: 7.7,
    id: '40470288',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'Stefon Diggs',
    nameAbbrev: 'S. Diggs',
    opposingTeamAbbrev: 'CLE',
    position: 'WR',
    salary: 5800,
    teamAbbrev: 'NE',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'MIA@ATL',
    gradeOutOfTen: 7.6,
    id: '40470294',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'Jaylen Waddle',
    nameAbbrev: 'J. Waddle',
    opposingTeamAbbrev: 'ATL',
    position: 'WR',
    salary: 5700,
    teamAbbrev: 'MIA',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TEN@IND',
    gradeOutOfTen: 7.5,
    id: '40470298',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'Michael Pittman Jr.',
    nameAbbrev: 'M. Pittman Jr.',
    opposingTeamAbbrev: 'TEN',
    position: 'WR',
    salary: 5600,
    teamAbbrev: 'IND',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'NYJ@CIN',
    gradeOutOfTen: 7.4,
    id: '40470296',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'Tee Higgins',
    nameAbbrev: 'T. Higgins',
    opposingTeamAbbrev: 'NYJ',
    position: 'WR',
    salary: 5600,
    teamAbbrev: 'CIN',
    maxOwnershipWhenPairedWithQb: 65,
    minOwnershipWhenPairedWithQb: 45,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 7.3,
    id: '40470270',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'George Pickens',
    nameAbbrev: 'G. Pickens',
    opposingTeamAbbrev: 'DEN',
    position: 'WR',
    salary: 7100,
    teamAbbrev: 'DAL',
    maxOwnershipWhenPairedWithQb: 50,
    minOwnershipWhenPairedWithQb: 30,
    maxOwnershipWhenPairedWithOpposingQb: 33,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 7.2,
    id: '40470330',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 13,
    minOwnershipPercentage: 5,
    name: 'Sterling Shepard',
    nameAbbrev: 'S. Shepard',
    opposingTeamAbbrev: 'NO',
    position: 'WR',
    salary: 4500,
    teamAbbrev: 'TB',
    maxOwnershipWhenPairedWithQb: 50,
    minOwnershipWhenPairedWithQb: 25,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 7.1,
    id: '40470338',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 0,
    name: 'Troy Franklin',
    nameAbbrev: 'T. Franklin',
    opposingTeamAbbrev: 'DAL',
    position: 'WR',
    salary: 4200,
    teamAbbrev: 'DEN',
    maxOwnershipWhenPairedWithQb: 20,
    minOwnershipWhenPairedWithQb: 12,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'SF@HOU',
    gradeOutOfTen: 7,
    id: '40470376',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 12,
    minOwnershipPercentage: 5,
    name: 'Jayden Higgins',
    nameAbbrev: 'J. Higgins',
    opposingTeamAbbrev: 'SF',
    position: 'WR',
    salary: 3500,
    teamAbbrev: 'HOU',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TEN@IND',
    gradeOutOfTen: 6.9,
    id: '40470384',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 5,
    name: 'Chimere Dike',
    nameAbbrev: 'C. Dike',
    opposingTeamAbbrev: 'IND',
    position: 'WR',
    salary: 3400,
    teamAbbrev: 'TEN',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 6.8,
    id: '40470306',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 0,
    name: 'DJ Moore',
    nameAbbrev: 'D. Moore',
    opposingTeamAbbrev: 'BAL',
    position: 'WR',
    salary: 5300,
    teamAbbrev: 'CHI',
    maxOwnershipWhenPairedWithQb: 20,
    minOwnershipWhenPairedWithQb: 8,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'BUF@CAR',
    gradeOutOfTen: 6.7,
    id: '40470350',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 0,
    name: 'Xavier Legette',
    nameAbbrev: 'X. Legette',
    opposingTeamAbbrev: 'BUF',
    position: 'WR',
    salary: 4000,
    teamAbbrev: 'CAR',
    maxOwnershipWhenPairedWithQb: 25,
    minOwnershipWhenPairedWithQb: 15,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'DAL@DEN',
    gradeOutOfTen: 6.6,
    id: '40470354',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 0,
    name: 'Marvin Mims Jr.',
    nameAbbrev: 'M. Mims Jr.',
    opposingTeamAbbrev: 'DAL',
    position: 'WR',
    salary: 3900,
    teamAbbrev: 'DEN',
    maxOwnershipWhenPairedWithQb: 15,
    minOwnershipWhenPairedWithQb: 8,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'BUF@CAR',
    gradeOutOfTen: 6.5,
    id: '40470358',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 0,
    name: 'Jalen Coker',
    nameAbbrev: 'J. Coker',
    opposingTeamAbbrev: 'BUF',
    position: 'WR',
    salary: 3800,
    teamAbbrev: 'CAR',
    maxOwnershipWhenPairedWithQb: 15,
    minOwnershipWhenPairedWithQb: 8,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 6.4,
    id: '40470360',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 0,
    name: 'Luther Burden III',
    nameAbbrev: 'L. Burden III',
    opposingTeamAbbrev: 'BAL',
    position: 'WR',
    salary: 3800,
    teamAbbrev: 'CHI',
    maxOwnershipWhenPairedWithQb: 12,
    minOwnershipWhenPairedWithQb: 5,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'MIA@ATL',
    gradeOutOfTen: 6.3,
    id: '40470276',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 0,
    minOwnershipPercentage: 0,
    name: 'Drake London',
    nameAbbrev: 'D. London',
    opposingTeamAbbrev: 'MIA',
    position: 'WR',
    salary: 6400,
    teamAbbrev: 'ATL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
];

export const selectedTightEnds: TightEnd[] = [
  {
    gameInfo: 'SF@HOU',
    gradeOutOfTen: 9,
    id: '40470686',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 32,
    minOwnershipPercentage: 25,
    name: 'Dalton Schultz',
    nameAbbrev: 'D. Schultz',
    opposingTeamAbbrev: 'SF',
    position: 'TE',
    salary: 3300,
    teamAbbrev: 'HOU',
    maxOwnershipWhenPairedWithQb: 0,
    minOwnershipWhenPairedWithQb: 0,
    maxOwnershipWhenPairedWithOpposingQb: 0,
    minOwnershipWhenPairedWithOpposingQb: 0,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'NYG@PHI',
    gradeOutOfTen: 8.9,
    id: '40470666',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 30,
    minOwnershipPercentage: 22,
    name: 'Dallas Goedert',
    nameAbbrev: 'D. Goedert',
    opposingTeamAbbrev: 'NYG',
    position: 'TE',
    salary: 4200,
    teamAbbrev: 'PHI',
    maxOwnershipWhenPairedWithQb: 0,
    minOwnershipWhenPairedWithQb: 0,
    maxOwnershipWhenPairedWithOpposingQb: 0,
    minOwnershipWhenPairedWithOpposingQb: 0,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.8,
    id: '40470698',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 18,
    name: 'Colston Loveland',
    nameAbbrev: 'C. Loveland',
    opposingTeamAbbrev: 'BAL',
    position: 'TE',
    salary: 3000,
    teamAbbrev: 'CHI',
    maxOwnershipWhenPairedWithQb: 50,
    minOwnershipWhenPairedWithQb: 30,
    maxOwnershipWhenPairedWithOpposingQb: 0,
    minOwnershipWhenPairedWithOpposingQb: 0,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'SF@HOU',
    gradeOutOfTen: 8.7,
    id: '40470660',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 9,
    minOwnershipPercentage: 1,
    name: 'George Kittle',
    nameAbbrev: 'G. Kittle',
    opposingTeamAbbrev: 'HOU',
    position: 'TE',
    salary: 4500,
    teamAbbrev: 'SF',
    maxOwnershipWhenPairedWithQb: 0,
    minOwnershipWhenPairedWithQb: 0,
    maxOwnershipWhenPairedWithOpposingQb: 0,
    minOwnershipWhenPairedWithOpposingQb: 0,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'TB@NO',
    gradeOutOfTen: 8.6,
    id: '40470684',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 12,
    minOwnershipPercentage: 0,
    name: 'Cade Otton',
    nameAbbrev: 'C. Otton',
    opposingTeamAbbrev: 'NO',
    position: 'TE',
    salary: 3400,
    teamAbbrev: 'TB',
    maxOwnershipWhenPairedWithQb: 50,
    minOwnershipWhenPairedWithQb: 30,
    maxOwnershipWhenPairedWithOpposingQb: 20,
    minOwnershipWhenPairedWithOpposingQb: 10,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'MIA@ATL',
    gradeOutOfTen: 8.5,
    id: '40470672',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 15,
    minOwnershipPercentage: 7,
    name: 'Kyle Pitts Sr.',
    nameAbbrev: 'K. Pitts Sr.',
    opposingTeamAbbrev: 'MIA',
    position: 'TE',
    salary: 3900,
    teamAbbrev: 'ATL',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
  {
    gameInfo: 'NYJ@CIN',
    gradeOutOfTen: 8.5,
    id: '40470690',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 15,
    minOwnershipPercentage: 0,
    name: 'Noah Fant',
    nameAbbrev: 'N. Fant',
    opposingTeamAbbrev: 'NYJ',
    position: 'TE',
    salary: 3200,
    teamAbbrev: 'CIN',
    maxOwnershipWhenPairedWithQb: 50,
    minOwnershipWhenPairedWithQb: 25,
    maxOwnershipWhenPairedWithOpposingQb: 0,
    minOwnershipWhenPairedWithOpposingQb: 0,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: true,
  },
  {
    gameInfo: 'CLE@NE',
    gradeOutOfTen: 8.4,
    id: '40470662',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 10,
    minOwnershipPercentage: 0,
    name: 'Harold Fannin Jr.',
    nameAbbrev: 'H. Fannin Jr.',
    opposingTeamAbbrev: 'NE',
    position: 'TE',
    salary: 4400,
    teamAbbrev: 'CLE',
    maxOwnershipWhenPairedWithQb: 80,
    minOwnershipWhenPairedWithQb: 20,
    maxOwnershipWhenPairedWithOpposingQb: 65,
    minOwnershipWhenPairedWithOpposingQb: 20,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },

  {
    gameInfo: 'NYJ@CIN',
    gradeOutOfTen: 8.2,
    id: '40470680',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 10,
    minOwnershipPercentage: 0,
    name: 'Mason Taylor',
    nameAbbrev: 'M. Taylor',
    opposingTeamAbbrev: 'CIN',
    position: 'TE',
    salary: 3500,
    teamAbbrev: 'NYJ',
    maxOwnershipWhenPairedWithQb: 0,
    minOwnershipWhenPairedWithQb: 0,
    maxOwnershipWhenPairedWithOpposingQb: 15,
    minOwnershipWhenPairedWithOpposingQb: 8,
    onlyUseIfPartOfStackOrPlayingWithOrAgainstQb: false,
  },
];

export const selectedDSTs: Player[] = [
  {
    gameInfo: 'NYJ@CIN',
    gradeOutOfTen: 8.8,
    id: '40470880',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 30,
    minOwnershipPercentage: 22,
    name: 'Bengals',
    nameAbbrev: 'Bengals',
    opposingTeamAbbrev: 'NYJ',
    position: 'DST',
    salary: 2700,
    teamAbbrev: 'CIN',
  },
  {
    gameInfo: 'TEN@IND',
    gradeOutOfTen: 8.7,
    id: '40470870',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 25,
    minOwnershipPercentage: 17,
    name: 'Colts',
    nameAbbrev: 'Colts',
    opposingTeamAbbrev: 'TEN',
    position: 'DST',
    salary: 3800,
    teamAbbrev: 'IND',
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8.6,
    id: '40470879',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 23,
    minOwnershipPercentage: 15,
    name: 'Ravens',
    nameAbbrev: 'Ravens',
    opposingTeamAbbrev: 'CHI',
    position: 'DST',
    salary: 2800,
    teamAbbrev: 'BAL',
  },
  {
    gameInfo: 'CLE@NE',
    gradeOutOfTen: 8.5,
    id: '40470882',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 20,
    minOwnershipPercentage: 12,
    name: 'Browns',
    nameAbbrev: 'Browns',
    opposingTeamAbbrev: 'NE',
    position: 'DST',
    salary: 2500,
    teamAbbrev: 'CLE',
  },
  {
    gameInfo: 'MIA@ATL',
    gradeOutOfTen: 8.3,
    id: '40470872',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 18,
    minOwnershipPercentage: 10,
    name: 'Falcons',
    nameAbbrev: 'Falcons',
    opposingTeamAbbrev: 'MIA',
    position: 'DST',
    salary: 3500,
    teamAbbrev: 'ATL',
  },
  {
    gameInfo: 'NYG@PHI',
    gradeOutOfTen: 8.2,
    id: '40470875',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 15,
    minOwnershipPercentage: 7,
    name: 'Eagles',
    nameAbbrev: 'Eagles',
    opposingTeamAbbrev: 'NYG',
    position: 'DST',
    salary: 3200,
    teamAbbrev: 'PHI',
  },
  {
    gameInfo: 'NYG@PHI',
    gradeOutOfTen: 8.1,
    id: '40470888',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 12,
    minOwnershipPercentage: 4,
    name: 'Giants',
    nameAbbrev: 'Giants',
    opposingTeamAbbrev: 'PHI',
    position: 'DST',
    salary: 2100,
    teamAbbrev: 'NYG',
  },
  {
    gameInfo: 'CHI@BAL',
    gradeOutOfTen: 8,
    id: '40470881',
    isSelectedForPlayerPool: false,
    maxOwnershipPercentage: 8,
    minOwnershipPercentage: 0,
    name: 'Bears',
    nameAbbrev: 'Bears',
    opposingTeamAbbrev: 'BAL',
    position: 'DST',
    salary: 2600,
    teamAbbrev: 'CHI',
  },
];
